/*
 * Automatically generated by code_gen/bidi_bracket_data.hpp
 * DO NOT EDIT!!
 */

#pragma once


#include <algorithm>
#include <array>
#include <cstdint>

#include "jcu/unicode_version.hpp"


namespace jcu::bidi {


enum class BracketPairedType : uint8_t {
    NONE,
    OPEN,
    CLOSE
};


struct BracketDataUnit {
    char32_t paired_code_point{0};
    BracketPairedType bracket_paired_type{BracketPairedType::NONE};
};


class BracketData {
public:
    using value_type = BracketDataUnit;

    static constexpr auto begin() noexcept { return data.cbegin(); }
    static constexpr auto end() noexcept { return data.cend(); }

    static constexpr value_type Lookup(char32_t code_point) noexcept {
        auto it = std::ranges::lower_bound(data, code_point, {}, &Data::code_point);
        if (it == data.end() || it->code_point != code_point) { return {}; }
        return std::ranges::prev(it)->value;
    }

    static constexpr const UnicodeVersion &Version() noexcept { return version; }

private:
    struct Data {
        char32_t code_point;
        value_type value;
    };

    static constexpr UnicodeVersion version{.major=15, .minor=1, .micro=0};
    static constexpr std::array<Data, 128> data{{
        Data{.code_point=0x28, .value={.paired_code_point=0x29, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x29, .value={.paired_code_point=0x28, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x5b, .value={.paired_code_point=0x5d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x5d, .value={.paired_code_point=0x5b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x7b, .value={.paired_code_point=0x7d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x7d, .value={.paired_code_point=0x7b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xf3a, .value={.paired_code_point=0xf3b, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xf3b, .value={.paired_code_point=0xf3a, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xf3c, .value={.paired_code_point=0xf3d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xf3d, .value={.paired_code_point=0xf3c, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x169b, .value={.paired_code_point=0x169c, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x169c, .value={.paired_code_point=0x169b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2045, .value={.paired_code_point=0x2046, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2046, .value={.paired_code_point=0x2045, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x207d, .value={.paired_code_point=0x207e, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x207e, .value={.paired_code_point=0x207d, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x208d, .value={.paired_code_point=0x208e, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x208e, .value={.paired_code_point=0x208d, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2308, .value={.paired_code_point=0x2309, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2309, .value={.paired_code_point=0x2308, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x230a, .value={.paired_code_point=0x230b, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x230b, .value={.paired_code_point=0x230a, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2329, .value={.paired_code_point=0x232a, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x232a, .value={.paired_code_point=0x2329, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2768, .value={.paired_code_point=0x2769, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2769, .value={.paired_code_point=0x2768, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x276a, .value={.paired_code_point=0x276b, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x276b, .value={.paired_code_point=0x276a, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x276c, .value={.paired_code_point=0x276d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x276d, .value={.paired_code_point=0x276c, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x276e, .value={.paired_code_point=0x276f, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x276f, .value={.paired_code_point=0x276e, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2770, .value={.paired_code_point=0x2771, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2771, .value={.paired_code_point=0x2770, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2772, .value={.paired_code_point=0x2773, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2773, .value={.paired_code_point=0x2772, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2774, .value={.paired_code_point=0x2775, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2775, .value={.paired_code_point=0x2774, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27c5, .value={.paired_code_point=0x27c6, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27c6, .value={.paired_code_point=0x27c5, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27e6, .value={.paired_code_point=0x27e7, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27e7, .value={.paired_code_point=0x27e6, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27e8, .value={.paired_code_point=0x27e9, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27e9, .value={.paired_code_point=0x27e8, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27ea, .value={.paired_code_point=0x27eb, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27eb, .value={.paired_code_point=0x27ea, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27ec, .value={.paired_code_point=0x27ed, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27ed, .value={.paired_code_point=0x27ec, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x27ee, .value={.paired_code_point=0x27ef, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x27ef, .value={.paired_code_point=0x27ee, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2983, .value={.paired_code_point=0x2984, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2984, .value={.paired_code_point=0x2983, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2985, .value={.paired_code_point=0x2986, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2986, .value={.paired_code_point=0x2985, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2987, .value={.paired_code_point=0x2988, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2988, .value={.paired_code_point=0x2987, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2989, .value={.paired_code_point=0x298a, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x298a, .value={.paired_code_point=0x2989, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x298b, .value={.paired_code_point=0x298c, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x298c, .value={.paired_code_point=0x298b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x298d, .value={.paired_code_point=0x2990, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x298e, .value={.paired_code_point=0x298f, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x298f, .value={.paired_code_point=0x298e, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2990, .value={.paired_code_point=0x298d, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2991, .value={.paired_code_point=0x2992, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2992, .value={.paired_code_point=0x2991, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2993, .value={.paired_code_point=0x2994, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2994, .value={.paired_code_point=0x2993, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2995, .value={.paired_code_point=0x2996, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2996, .value={.paired_code_point=0x2995, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2997, .value={.paired_code_point=0x2998, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2998, .value={.paired_code_point=0x2997, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x29d8, .value={.paired_code_point=0x29d9, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x29d9, .value={.paired_code_point=0x29d8, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x29da, .value={.paired_code_point=0x29db, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x29db, .value={.paired_code_point=0x29da, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x29fc, .value={.paired_code_point=0x29fd, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x29fd, .value={.paired_code_point=0x29fc, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e22, .value={.paired_code_point=0x2e23, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e23, .value={.paired_code_point=0x2e22, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e24, .value={.paired_code_point=0x2e25, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e25, .value={.paired_code_point=0x2e24, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e26, .value={.paired_code_point=0x2e27, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e27, .value={.paired_code_point=0x2e26, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e28, .value={.paired_code_point=0x2e29, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e29, .value={.paired_code_point=0x2e28, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e55, .value={.paired_code_point=0x2e56, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e56, .value={.paired_code_point=0x2e55, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e57, .value={.paired_code_point=0x2e58, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e58, .value={.paired_code_point=0x2e57, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e59, .value={.paired_code_point=0x2e5a, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e5a, .value={.paired_code_point=0x2e59, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x2e5b, .value={.paired_code_point=0x2e5c, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x2e5c, .value={.paired_code_point=0x2e5b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x3008, .value={.paired_code_point=0x3009, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x3009, .value={.paired_code_point=0x3008, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x300a, .value={.paired_code_point=0x300b, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x300b, .value={.paired_code_point=0x300a, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x300c, .value={.paired_code_point=0x300d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x300d, .value={.paired_code_point=0x300c, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x300e, .value={.paired_code_point=0x300f, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x300f, .value={.paired_code_point=0x300e, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x3010, .value={.paired_code_point=0x3011, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x3011, .value={.paired_code_point=0x3010, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x3014, .value={.paired_code_point=0x3015, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x3015, .value={.paired_code_point=0x3014, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x3016, .value={.paired_code_point=0x3017, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x3017, .value={.paired_code_point=0x3016, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x3018, .value={.paired_code_point=0x3019, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x3019, .value={.paired_code_point=0x3018, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0x301a, .value={.paired_code_point=0x301b, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0x301b, .value={.paired_code_point=0x301a, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xfe59, .value={.paired_code_point=0xfe5a, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xfe5a, .value={.paired_code_point=0xfe59, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xfe5b, .value={.paired_code_point=0xfe5c, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xfe5c, .value={.paired_code_point=0xfe5b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xfe5d, .value={.paired_code_point=0xfe5e, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xfe5e, .value={.paired_code_point=0xfe5d, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xff08, .value={.paired_code_point=0xff09, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xff09, .value={.paired_code_point=0xff08, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xff3b, .value={.paired_code_point=0xff3d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xff3d, .value={.paired_code_point=0xff3b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xff5b, .value={.paired_code_point=0xff5d, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xff5d, .value={.paired_code_point=0xff5b, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xff5f, .value={.paired_code_point=0xff60, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xff60, .value={.paired_code_point=0xff5f, .bracket_paired_type=BracketPairedType::CLOSE}},
        Data{.code_point=0xff62, .value={.paired_code_point=0xff63, .bracket_paired_type=BracketPairedType::OPEN}},
        Data{.code_point=0xff63, .value={.paired_code_point=0xff62, .bracket_paired_type=BracketPairedType::CLOSE}}
    }};
};


}
