// Copyright © 2024 Jason Stredwick

/***
 * TODO: Figure out how to convert these mapping functions to something other than repeated if statements.
 */

#pragma once


#include <string>
#include <string_view>

#include "jcu/script.hpp"


namespace jcu {


constexpr Script ScriptFromAliasString(std::string_view sv) {
    if (sv == std::string_view{"ZINH"}) { return Script::ZINH; }
    if (sv == std::string_view{"ZYYY"}) { return Script::ZYYY; }
    if (sv == std::string_view{"ZZZZ"}) { return Script::ZZZZ; }
    if (sv == std::string_view{"ARAB"}) { return Script::ARAB; }
    if (sv == std::string_view{"ARMN"}) { return Script::ARMN; }
    if (sv == std::string_view{"BENG"}) { return Script::BENG; }
    if (sv == std::string_view{"BOPO"}) { return Script::BOPO; }
    if (sv == std::string_view{"CYRL"}) { return Script::CYRL; }
    if (sv == std::string_view{"DEVA"}) { return Script::DEVA; }
    if (sv == std::string_view{"GEOR"}) { return Script::GEOR; }
    if (sv == std::string_view{"GREK"}) { return Script::GREK; }
    if (sv == std::string_view{"GUJR"}) { return Script::GUJR; }
    if (sv == std::string_view{"GURU"}) { return Script::GURU; }
    if (sv == std::string_view{"HANG"}) { return Script::HANG; }
    if (sv == std::string_view{"HANI"}) { return Script::HANI; }
    if (sv == std::string_view{"HEBR"}) { return Script::HEBR; }
    if (sv == std::string_view{"HIRA"}) { return Script::HIRA; }
    if (sv == std::string_view{"KANA"}) { return Script::KANA; }
    if (sv == std::string_view{"KNDA"}) { return Script::KNDA; }
    if (sv == std::string_view{"LAOO"}) { return Script::LAOO; }
    if (sv == std::string_view{"LATN"}) { return Script::LATN; }
    if (sv == std::string_view{"MLYM"}) { return Script::MLYM; }
    if (sv == std::string_view{"ORYA"}) { return Script::ORYA; }
    if (sv == std::string_view{"TAML"}) { return Script::TAML; }
    if (sv == std::string_view{"TELU"}) { return Script::TELU; }
    if (sv == std::string_view{"THAI"}) { return Script::THAI; }
    if (sv == std::string_view{"TIBT"}) { return Script::TIBT; }
    if (sv == std::string_view{"BRAI"}) { return Script::BRAI; }
    if (sv == std::string_view{"CANS"}) { return Script::CANS; }
    if (sv == std::string_view{"CHER"}) { return Script::CHER; }
    if (sv == std::string_view{"ETHI"}) { return Script::ETHI; }
    if (sv == std::string_view{"KHMR"}) { return Script::KHMR; }
    if (sv == std::string_view{"MONG"}) { return Script::MONG; }
    if (sv == std::string_view{"MYMR"}) { return Script::MYMR; }
    if (sv == std::string_view{"OGAM"}) { return Script::OGAM; }
    if (sv == std::string_view{"RUNR"}) { return Script::RUNR; }
    if (sv == std::string_view{"SINH"}) { return Script::SINH; }
    if (sv == std::string_view{"SYRC"}) { return Script::SYRC; }
    if (sv == std::string_view{"THAA"}) { return Script::THAA; }
    if (sv == std::string_view{"YIII"}) { return Script::YIII; }
    if (sv == std::string_view{"DSRT"}) { return Script::DSRT; }
    if (sv == std::string_view{"GOTH"}) { return Script::GOTH; }
    if (sv == std::string_view{"ITAL"}) { return Script::ITAL; }
    if (sv == std::string_view{"BUHD"}) { return Script::BUHD; }
    if (sv == std::string_view{"HANO"}) { return Script::HANO; }
    if (sv == std::string_view{"TAGB"}) { return Script::TAGB; }
    if (sv == std::string_view{"TGLG"}) { return Script::TGLG; }
    if (sv == std::string_view{"CPRT"}) { return Script::CPRT; }
    if (sv == std::string_view{"LIMB"}) { return Script::LIMB; }
    if (sv == std::string_view{"LINB"}) { return Script::LINB; }
    if (sv == std::string_view{"OSMA"}) { return Script::OSMA; }
    if (sv == std::string_view{"SHAW"}) { return Script::SHAW; }
    if (sv == std::string_view{"TALE"}) { return Script::TALE; }
    if (sv == std::string_view{"UGAR"}) { return Script::UGAR; }
    if (sv == std::string_view{"BUGI"}) { return Script::BUGI; }
    if (sv == std::string_view{"COPT"}) { return Script::COPT; }
    if (sv == std::string_view{"GLAG"}) { return Script::GLAG; }
    if (sv == std::string_view{"KHAR"}) { return Script::KHAR; }
    if (sv == std::string_view{"SYLO"}) { return Script::SYLO; }
    if (sv == std::string_view{"TALU"}) { return Script::TALU; }
    if (sv == std::string_view{"TFNG"}) { return Script::TFNG; }
    if (sv == std::string_view{"XPEO"}) { return Script::XPEO; }
    if (sv == std::string_view{"BALI"}) { return Script::BALI; }
    if (sv == std::string_view{"NKOO"}) { return Script::NKOO; }
    if (sv == std::string_view{"PHAG"}) { return Script::PHAG; }
    if (sv == std::string_view{"PHNX"}) { return Script::PHNX; }
    if (sv == std::string_view{"XSUX"}) { return Script::XSUX; }
    if (sv == std::string_view{"CARI"}) { return Script::CARI; }
    if (sv == std::string_view{"CHAM"}) { return Script::CHAM; }
    if (sv == std::string_view{"KALI"}) { return Script::KALI; }
    if (sv == std::string_view{"LEPC"}) { return Script::LEPC; }
    if (sv == std::string_view{"LYCI"}) { return Script::LYCI; }
    if (sv == std::string_view{"LYDI"}) { return Script::LYDI; }
    if (sv == std::string_view{"OLCK"}) { return Script::OLCK; }
    if (sv == std::string_view{"RJNG"}) { return Script::RJNG; }
    if (sv == std::string_view{"SAUR"}) { return Script::SAUR; }
    if (sv == std::string_view{"SUND"}) { return Script::SUND; }
    if (sv == std::string_view{"VAII"}) { return Script::VAII; }
    if (sv == std::string_view{"ARMI"}) { return Script::ARMI; }
    if (sv == std::string_view{"AVST"}) { return Script::AVST; }
    if (sv == std::string_view{"BAMU"}) { return Script::BAMU; }
    if (sv == std::string_view{"EGYP"}) { return Script::EGYP; }
    if (sv == std::string_view{"JAVA"}) { return Script::JAVA; }
    if (sv == std::string_view{"KTHI"}) { return Script::KTHI; }
    if (sv == std::string_view{"LANA"}) { return Script::LANA; }
    if (sv == std::string_view{"LISU"}) { return Script::LISU; }
    if (sv == std::string_view{"MTEI"}) { return Script::MTEI; }
    if (sv == std::string_view{"ORKH"}) { return Script::ORKH; }
    if (sv == std::string_view{"PHLI"}) { return Script::PHLI; }
    if (sv == std::string_view{"PRTI"}) { return Script::PRTI; }
    if (sv == std::string_view{"SAMR"}) { return Script::SAMR; }
    if (sv == std::string_view{"SARB"}) { return Script::SARB; }
    if (sv == std::string_view{"TAVT"}) { return Script::TAVT; }
    if (sv == std::string_view{"BATK"}) { return Script::BATK; }
    if (sv == std::string_view{"BRAH"}) { return Script::BRAH; }
    if (sv == std::string_view{"MAND"}) { return Script::MAND; }
    if (sv == std::string_view{"CAKM"}) { return Script::CAKM; }
    if (sv == std::string_view{"MERC"}) { return Script::MERC; }
    if (sv == std::string_view{"MERO"}) { return Script::MERO; }
    if (sv == std::string_view{"PLRD"}) { return Script::PLRD; }
    if (sv == std::string_view{"SHRD"}) { return Script::SHRD; }
    if (sv == std::string_view{"SORA"}) { return Script::SORA; }
    if (sv == std::string_view{"TAKR"}) { return Script::TAKR; }
    if (sv == std::string_view{"AGHB"}) { return Script::AGHB; }
    if (sv == std::string_view{"BASS"}) { return Script::BASS; }
    if (sv == std::string_view{"DUPL"}) { return Script::DUPL; }
    if (sv == std::string_view{"ELBA"}) { return Script::ELBA; }
    if (sv == std::string_view{"GRAN"}) { return Script::GRAN; }
    if (sv == std::string_view{"HMNG"}) { return Script::HMNG; }
    if (sv == std::string_view{"KHOJ"}) { return Script::KHOJ; }
    if (sv == std::string_view{"LINA"}) { return Script::LINA; }
    if (sv == std::string_view{"MAHJ"}) { return Script::MAHJ; }
    if (sv == std::string_view{"MANI"}) { return Script::MANI; }
    if (sv == std::string_view{"MEND"}) { return Script::MEND; }
    if (sv == std::string_view{"MODI"}) { return Script::MODI; }
    if (sv == std::string_view{"MROO"}) { return Script::MROO; }
    if (sv == std::string_view{"NARB"}) { return Script::NARB; }
    if (sv == std::string_view{"NBAT"}) { return Script::NBAT; }
    if (sv == std::string_view{"PALM"}) { return Script::PALM; }
    if (sv == std::string_view{"PAUC"}) { return Script::PAUC; }
    if (sv == std::string_view{"PERM"}) { return Script::PERM; }
    if (sv == std::string_view{"PHLP"}) { return Script::PHLP; }
    if (sv == std::string_view{"SIDD"}) { return Script::SIDD; }
    if (sv == std::string_view{"SIND"}) { return Script::SIND; }
    if (sv == std::string_view{"TIRH"}) { return Script::TIRH; }
    if (sv == std::string_view{"WARA"}) { return Script::WARA; }
    if (sv == std::string_view{"AHOM"}) { return Script::AHOM; }
    if (sv == std::string_view{"HATR"}) { return Script::HATR; }
    if (sv == std::string_view{"HLUW"}) { return Script::HLUW; }
    if (sv == std::string_view{"HUNG"}) { return Script::HUNG; }
    if (sv == std::string_view{"MULT"}) { return Script::MULT; }
    if (sv == std::string_view{"SGNW"}) { return Script::SGNW; }
    if (sv == std::string_view{"ADLM"}) { return Script::ADLM; }
    if (sv == std::string_view{"BHKS"}) { return Script::BHKS; }
    if (sv == std::string_view{"MARC"}) { return Script::MARC; }
    if (sv == std::string_view{"NEWA"}) { return Script::NEWA; }
    if (sv == std::string_view{"OSGE"}) { return Script::OSGE; }
    if (sv == std::string_view{"TANG"}) { return Script::TANG; }
    if (sv == std::string_view{"GONM"}) { return Script::GONM; }
    if (sv == std::string_view{"NSHU"}) { return Script::NSHU; }
    if (sv == std::string_view{"SOYO"}) { return Script::SOYO; }
    if (sv == std::string_view{"ZANB"}) { return Script::ZANB; }
    if (sv == std::string_view{"DOGR"}) { return Script::DOGR; }
    if (sv == std::string_view{"GONG"}) { return Script::GONG; }
    if (sv == std::string_view{"MAKA"}) { return Script::MAKA; }
    if (sv == std::string_view{"MEDF"}) { return Script::MEDF; }
    if (sv == std::string_view{"ROHG"}) { return Script::ROHG; }
    if (sv == std::string_view{"SOGD"}) { return Script::SOGD; }
    if (sv == std::string_view{"SOGO"}) { return Script::SOGO; }
    if (sv == std::string_view{"ELYM"}) { return Script::ELYM; }
    if (sv == std::string_view{"HMNP"}) { return Script::HMNP; }
    if (sv == std::string_view{"NAND"}) { return Script::NAND; }
    if (sv == std::string_view{"WCHO"}) { return Script::WCHO; }
    if (sv == std::string_view{"CHRS"}) { return Script::CHRS; }
    if (sv == std::string_view{"DIAK"}) { return Script::DIAK; }
    if (sv == std::string_view{"KITS"}) { return Script::KITS; }
    if (sv == std::string_view{"YEZI"}) { return Script::YEZI; }
    if (sv == std::string_view{"CPMN"}) { return Script::CPMN; }
    if (sv == std::string_view{"OUGR"}) { return Script::OUGR; }
    if (sv == std::string_view{"TNSA"}) { return Script::TNSA; }
    if (sv == std::string_view{"TOTO"}) { return Script::TOTO; }
    if (sv == std::string_view{"VITH"}) { return Script::VITH; }
    if (sv == std::string_view{"KAWI"}) { return Script::KAWI; }
    if (sv == std::string_view{"NAGM"}) { return Script::NAGM; }
    return Script::NIL;
}


constexpr Script ScriptFromString(std::string_view sv) {
    if (sv == std::string_view{"Inherited"}) { return Script::ZINH; }
    if (sv == std::string_view{"Common"}) { return Script::ZYYY; }
    if (sv == std::string_view{"Unknown"}) { return Script::ZZZZ; }
    if (sv == std::string_view{"Arabic"}) { return Script::ARAB; }
    if (sv == std::string_view{"Armenian"}) { return Script::ARMN; }
    if (sv == std::string_view{"Bengali"}) { return Script::BENG; }
    if (sv == std::string_view{"Bopomofo"}) { return Script::BOPO; }
    if (sv == std::string_view{"Cyrillic"}) { return Script::CYRL; }
    if (sv == std::string_view{"Devanagari"}) { return Script::DEVA; }
    if (sv == std::string_view{"Georgian"}) { return Script::GEOR; }
    if (sv == std::string_view{"Greek"}) { return Script::GREK; }
    if (sv == std::string_view{"Gujarati"}) { return Script::GUJR; }
    if (sv == std::string_view{"Gurmukhi"}) { return Script::GURU; }
    if (sv == std::string_view{"Hangul"}) { return Script::HANG; }
    if (sv == std::string_view{"Han"}) { return Script::HANI; }
    if (sv == std::string_view{"Hebrew"}) { return Script::HEBR; }
    if (sv == std::string_view{"Hiragana"}) { return Script::HIRA; }
    if (sv == std::string_view{"Katakana"}) { return Script::KANA; }
    if (sv == std::string_view{"Kannada"}) { return Script::KNDA; }
    if (sv == std::string_view{"Lao"}) { return Script::LAOO; }
    if (sv == std::string_view{"Latin"}) { return Script::LATN; }
    if (sv == std::string_view{"Malayalam"}) { return Script::MLYM; }
    if (sv == std::string_view{"Oriya"}) { return Script::ORYA; }
    if (sv == std::string_view{"Tamil"}) { return Script::TAML; }
    if (sv == std::string_view{"Telugu"}) { return Script::TELU; }
    if (sv == std::string_view{"Thai"}) { return Script::THAI; }
    if (sv == std::string_view{"Tibetan"}) { return Script::TIBT; }
    if (sv == std::string_view{"Braille"}) { return Script::BRAI; }
    if (sv == std::string_view{"Canadian_Aboriginal"}) { return Script::CANS; }
    if (sv == std::string_view{"Cherokee"}) { return Script::CHER; }
    if (sv == std::string_view{"Ethiopic"}) { return Script::ETHI; }
    if (sv == std::string_view{"Khmer"}) { return Script::KHMR; }
    if (sv == std::string_view{"Mongolian"}) { return Script::MONG; }
    if (sv == std::string_view{"Myanmar"}) { return Script::MYMR; }
    if (sv == std::string_view{"Ogham"}) { return Script::OGAM; }
    if (sv == std::string_view{"Runic"}) { return Script::RUNR; }
    if (sv == std::string_view{"Sinhala"}) { return Script::SINH; }
    if (sv == std::string_view{"Syriac"}) { return Script::SYRC; }
    if (sv == std::string_view{"Thaana"}) { return Script::THAA; }
    if (sv == std::string_view{"Yi"}) { return Script::YIII; }
    if (sv == std::string_view{"Deseret"}) { return Script::DSRT; }
    if (sv == std::string_view{"Gothic"}) { return Script::GOTH; }
    if (sv == std::string_view{"Old_Italic"}) { return Script::ITAL; }
    if (sv == std::string_view{"Buhid"}) { return Script::BUHD; }
    if (sv == std::string_view{"Hanunoo"}) { return Script::HANO; }
    if (sv == std::string_view{"Tagbanwa"}) { return Script::TAGB; }
    if (sv == std::string_view{"Tagalog"}) { return Script::TGLG; }
    if (sv == std::string_view{"Cypriot"}) { return Script::CPRT; }
    if (sv == std::string_view{"Limbu"}) { return Script::LIMB; }
    if (sv == std::string_view{"Linear_B"}) { return Script::LINB; }
    if (sv == std::string_view{"Osmanya"}) { return Script::OSMA; }
    if (sv == std::string_view{"Shavian"}) { return Script::SHAW; }
    if (sv == std::string_view{"Tai_Le"}) { return Script::TALE; }
    if (sv == std::string_view{"Ugaritic"}) { return Script::UGAR; }
    if (sv == std::string_view{"Buginese"}) { return Script::BUGI; }
    if (sv == std::string_view{"Coptic"}) { return Script::COPT; }
    if (sv == std::string_view{"Glagolitic"}) { return Script::GLAG; }
    if (sv == std::string_view{"Kharoshthi"}) { return Script::KHAR; }
    if (sv == std::string_view{"Syloti_Nagri"}) { return Script::SYLO; }
    if (sv == std::string_view{"New_Tai_Lue"}) { return Script::TALU; }
    if (sv == std::string_view{"Tifinagh"}) { return Script::TFNG; }
    if (sv == std::string_view{"Old_Persian"}) { return Script::XPEO; }
    if (sv == std::string_view{"Balinese"}) { return Script::BALI; }
    if (sv == std::string_view{"Nko"}) { return Script::NKOO; }
    if (sv == std::string_view{"Phags_Pa"}) { return Script::PHAG; }
    if (sv == std::string_view{"Phoenician"}) { return Script::PHNX; }
    if (sv == std::string_view{"Cuneiform"}) { return Script::XSUX; }
    if (sv == std::string_view{"Carian"}) { return Script::CARI; }
    if (sv == std::string_view{"Cham"}) { return Script::CHAM; }
    if (sv == std::string_view{"Kayah_Li"}) { return Script::KALI; }
    if (sv == std::string_view{"Lepcha"}) { return Script::LEPC; }
    if (sv == std::string_view{"Lycian"}) { return Script::LYCI; }
    if (sv == std::string_view{"Lydian"}) { return Script::LYDI; }
    if (sv == std::string_view{"Ol_Chiki"}) { return Script::OLCK; }
    if (sv == std::string_view{"Rejang"}) { return Script::RJNG; }
    if (sv == std::string_view{"Saurashtra"}) { return Script::SAUR; }
    if (sv == std::string_view{"Sundanese"}) { return Script::SUND; }
    if (sv == std::string_view{"Vai"}) { return Script::VAII; }
    if (sv == std::string_view{"Imperial_Aramaic"}) { return Script::ARMI; }
    if (sv == std::string_view{"Avestan"}) { return Script::AVST; }
    if (sv == std::string_view{"Bamum"}) { return Script::BAMU; }
    if (sv == std::string_view{"Egyptian_Hieroglyphs"}) { return Script::EGYP; }
    if (sv == std::string_view{"Javanese"}) { return Script::JAVA; }
    if (sv == std::string_view{"Kaithi"}) { return Script::KTHI; }
    if (sv == std::string_view{"Tai_Tham"}) { return Script::LANA; }
    if (sv == std::string_view{"Lisu"}) { return Script::LISU; }
    if (sv == std::string_view{"Meetei_Mayek"}) { return Script::MTEI; }
    if (sv == std::string_view{"Old_Turkic"}) { return Script::ORKH; }
    if (sv == std::string_view{"Inscriptional_Pahlavi"}) { return Script::PHLI; }
    if (sv == std::string_view{"Inscriptional_Parthian"}) { return Script::PRTI; }
    if (sv == std::string_view{"Samaritan"}) { return Script::SAMR; }
    if (sv == std::string_view{"Old_South_Arabian"}) { return Script::SARB; }
    if (sv == std::string_view{"Tai_Viet"}) { return Script::TAVT; }
    if (sv == std::string_view{"Batak"}) { return Script::BATK; }
    if (sv == std::string_view{"Brahmi"}) { return Script::BRAH; }
    if (sv == std::string_view{"Mandaic"}) { return Script::MAND; }
    if (sv == std::string_view{"Chakma"}) { return Script::CAKM; }
    if (sv == std::string_view{"Meroitic_Cursive"}) { return Script::MERC; }
    if (sv == std::string_view{"Meroitic_Hieroglyphs"}) { return Script::MERO; }
    if (sv == std::string_view{"Miao"}) { return Script::PLRD; }
    if (sv == std::string_view{"Sharada"}) { return Script::SHRD; }
    if (sv == std::string_view{"Sora_Sompeng"}) { return Script::SORA; }
    if (sv == std::string_view{"Takri"}) { return Script::TAKR; }
    if (sv == std::string_view{"Caucasian_Albanian"}) { return Script::AGHB; }
    if (sv == std::string_view{"Bassa_Vah"}) { return Script::BASS; }
    if (sv == std::string_view{"Duployan"}) { return Script::DUPL; }
    if (sv == std::string_view{"Elbasan"}) { return Script::ELBA; }
    if (sv == std::string_view{"Grantha"}) { return Script::GRAN; }
    if (sv == std::string_view{"Pahawh_Hmong"}) { return Script::HMNG; }
    if (sv == std::string_view{"Khojki"}) { return Script::KHOJ; }
    if (sv == std::string_view{"Linear_A"}) { return Script::LINA; }
    if (sv == std::string_view{"Mahajani"}) { return Script::MAHJ; }
    if (sv == std::string_view{"Manichaean"}) { return Script::MANI; }
    if (sv == std::string_view{"Mende_Kikakui"}) { return Script::MEND; }
    if (sv == std::string_view{"Modi"}) { return Script::MODI; }
    if (sv == std::string_view{"Mro"}) { return Script::MROO; }
    if (sv == std::string_view{"Old_North_Arabian"}) { return Script::NARB; }
    if (sv == std::string_view{"Nabataean"}) { return Script::NBAT; }
    if (sv == std::string_view{"Palmyrene"}) { return Script::PALM; }
    if (sv == std::string_view{"Pau_Cin_Hau"}) { return Script::PAUC; }
    if (sv == std::string_view{"Old_Permic"}) { return Script::PERM; }
    if (sv == std::string_view{"Psalter_Pahlavi"}) { return Script::PHLP; }
    if (sv == std::string_view{"Siddham"}) { return Script::SIDD; }
    if (sv == std::string_view{"Khudawadi"}) { return Script::SIND; }
    if (sv == std::string_view{"Tirhuta"}) { return Script::TIRH; }
    if (sv == std::string_view{"Warang_Citi"}) { return Script::WARA; }
    if (sv == std::string_view{"Ahom"}) { return Script::AHOM; }
    if (sv == std::string_view{"Hatran"}) { return Script::HATR; }
    if (sv == std::string_view{"Anatolian_Hieroglyphs"}) { return Script::HLUW; }
    if (sv == std::string_view{"Old_Hungarian"}) { return Script::HUNG; }
    if (sv == std::string_view{"Multani"}) { return Script::MULT; }
    if (sv == std::string_view{"SignWriting"}) { return Script::SGNW; }
    if (sv == std::string_view{"Adlam"}) { return Script::ADLM; }
    if (sv == std::string_view{"Bhaiksuki"}) { return Script::BHKS; }
    if (sv == std::string_view{"Marchen"}) { return Script::MARC; }
    if (sv == std::string_view{"Newa"}) { return Script::NEWA; }
    if (sv == std::string_view{"Osage"}) { return Script::OSGE; }
    if (sv == std::string_view{"Tangut"}) { return Script::TANG; }
    if (sv == std::string_view{"Masaram_Gondi"}) { return Script::GONM; }
    if (sv == std::string_view{"Nushu"}) { return Script::NSHU; }
    if (sv == std::string_view{"Soyombo"}) { return Script::SOYO; }
    if (sv == std::string_view{"Zanabazar_Square"}) { return Script::ZANB; }
    if (sv == std::string_view{"Dogra"}) { return Script::DOGR; }
    if (sv == std::string_view{"Gunjala_Gondi"}) { return Script::GONG; }
    if (sv == std::string_view{"Makasar"}) { return Script::MAKA; }
    if (sv == std::string_view{"Medefaidrin"}) { return Script::MEDF; }
    if (sv == std::string_view{"Hanifi_Rohingya"}) { return Script::ROHG; }
    if (sv == std::string_view{"Sogdian"}) { return Script::SOGD; }
    if (sv == std::string_view{"Old_Sogdian"}) { return Script::SOGO; }
    if (sv == std::string_view{"Elymaic"}) { return Script::ELYM; }
    if (sv == std::string_view{"Nyiakeng_Puachue_Hmong"}) { return Script::HMNP; }
    if (sv == std::string_view{"Nandinagari"}) { return Script::NAND; }
    if (sv == std::string_view{"Wancho"}) { return Script::WCHO; }
    if (sv == std::string_view{"Chorasmian"}) { return Script::CHRS; }
    if (sv == std::string_view{"Dives_Akuru"}) { return Script::DIAK; }
    if (sv == std::string_view{"Khitan_Small_Script"}) { return Script::KITS; }
    if (sv == std::string_view{"Yezidi"}) { return Script::YEZI; }
    if (sv == std::string_view{"Cypro_Minoan"}) { return Script::CPMN; }
    if (sv == std::string_view{"Old_Uyghur"}) { return Script::OUGR; }
    if (sv == std::string_view{"Tangsa"}) { return Script::TNSA; }
    if (sv == std::string_view{"Toto"}) { return Script::TOTO; }
    if (sv == std::string_view{"Vithkuqi"}) { return Script::VITH; }
    if (sv == std::string_view{"Kawi"}) { return Script::KAWI; }
    if (sv == std::string_view{"Nag_Mundari"}) { return Script::NAGM; }
    return Script::NIL;
}


constexpr std::string ToAliasString(Script value) {
    if (value == Script::ZINH) { return "ZINH"; }
    if (value == Script::ZYYY) { return "ZYYY"; }
    if (value == Script::ZZZZ) { return "ZZZZ"; }
    if (value == Script::ARAB) { return "ARAB"; }
    if (value == Script::ARMN) { return "ARMN"; }
    if (value == Script::BENG) { return "BENG"; }
    if (value == Script::BOPO) { return "BOPO"; }
    if (value == Script::CYRL) { return "CYRL"; }
    if (value == Script::DEVA) { return "DEVA"; }
    if (value == Script::GEOR) { return "GEOR"; }
    if (value == Script::GREK) { return "GREK"; }
    if (value == Script::GUJR) { return "GUJR"; }
    if (value == Script::GURU) { return "GURU"; }
    if (value == Script::HANG) { return "HANG"; }
    if (value == Script::HANI) { return "HANI"; }
    if (value == Script::HEBR) { return "HEBR"; }
    if (value == Script::HIRA) { return "HIRA"; }
    if (value == Script::KANA) { return "KANA"; }
    if (value == Script::KNDA) { return "KNDA"; }
    if (value == Script::LAOO) { return "LAOO"; }
    if (value == Script::LATN) { return "LATN"; }
    if (value == Script::MLYM) { return "MLYM"; }
    if (value == Script::ORYA) { return "ORYA"; }
    if (value == Script::TAML) { return "TAML"; }
    if (value == Script::TELU) { return "TELU"; }
    if (value == Script::THAI) { return "THAI"; }
    if (value == Script::TIBT) { return "TIBT"; }
    if (value == Script::BRAI) { return "BRAI"; }
    if (value == Script::CANS) { return "CANS"; }
    if (value == Script::CHER) { return "CHER"; }
    if (value == Script::ETHI) { return "ETHI"; }
    if (value == Script::KHMR) { return "KHMR"; }
    if (value == Script::MONG) { return "MONG"; }
    if (value == Script::MYMR) { return "MYMR"; }
    if (value == Script::OGAM) { return "OGAM"; }
    if (value == Script::RUNR) { return "RUNR"; }
    if (value == Script::SINH) { return "SINH"; }
    if (value == Script::SYRC) { return "SYRC"; }
    if (value == Script::THAA) { return "THAA"; }
    if (value == Script::YIII) { return "YIII"; }
    if (value == Script::DSRT) { return "DSRT"; }
    if (value == Script::GOTH) { return "GOTH"; }
    if (value == Script::ITAL) { return "ITAL"; }
    if (value == Script::BUHD) { return "BUHD"; }
    if (value == Script::HANO) { return "HANO"; }
    if (value == Script::TAGB) { return "TAGB"; }
    if (value == Script::TGLG) { return "TGLG"; }
    if (value == Script::CPRT) { return "CPRT"; }
    if (value == Script::LIMB) { return "LIMB"; }
    if (value == Script::LINB) { return "LINB"; }
    if (value == Script::OSMA) { return "OSMA"; }
    if (value == Script::SHAW) { return "SHAW"; }
    if (value == Script::TALE) { return "TALE"; }
    if (value == Script::UGAR) { return "UGAR"; }
    if (value == Script::BUGI) { return "BUGI"; }
    if (value == Script::COPT) { return "COPT"; }
    if (value == Script::GLAG) { return "GLAG"; }
    if (value == Script::KHAR) { return "KHAR"; }
    if (value == Script::SYLO) { return "SYLO"; }
    if (value == Script::TALU) { return "TALU"; }
    if (value == Script::TFNG) { return "TFNG"; }
    if (value == Script::XPEO) { return "XPEO"; }
    if (value == Script::BALI) { return "BALI"; }
    if (value == Script::NKOO) { return "NKOO"; }
    if (value == Script::PHAG) { return "PHAG"; }
    if (value == Script::PHNX) { return "PHNX"; }
    if (value == Script::XSUX) { return "XSUX"; }
    if (value == Script::CARI) { return "CARI"; }
    if (value == Script::CHAM) { return "CHAM"; }
    if (value == Script::KALI) { return "KALI"; }
    if (value == Script::LEPC) { return "LEPC"; }
    if (value == Script::LYCI) { return "LYCI"; }
    if (value == Script::LYDI) { return "LYDI"; }
    if (value == Script::OLCK) { return "OLCK"; }
    if (value == Script::RJNG) { return "RJNG"; }
    if (value == Script::SAUR) { return "SAUR"; }
    if (value == Script::SUND) { return "SUND"; }
    if (value == Script::VAII) { return "VAII"; }
    if (value == Script::ARMI) { return "ARMI"; }
    if (value == Script::AVST) { return "AVST"; }
    if (value == Script::BAMU) { return "BAMU"; }
    if (value == Script::EGYP) { return "EGYP"; }
    if (value == Script::JAVA) { return "JAVA"; }
    if (value == Script::KTHI) { return "KTHI"; }
    if (value == Script::LANA) { return "LANA"; }
    if (value == Script::LISU) { return "LISU"; }
    if (value == Script::MTEI) { return "MTEI"; }
    if (value == Script::ORKH) { return "ORKH"; }
    if (value == Script::PHLI) { return "PHLI"; }
    if (value == Script::PRTI) { return "PRTI"; }
    if (value == Script::SAMR) { return "SAMR"; }
    if (value == Script::SARB) { return "SARB"; }
    if (value == Script::TAVT) { return "TAVT"; }
    if (value == Script::BATK) { return "BATK"; }
    if (value == Script::BRAH) { return "BRAH"; }
    if (value == Script::MAND) { return "MAND"; }
    if (value == Script::CAKM) { return "CAKM"; }
    if (value == Script::MERC) { return "MERC"; }
    if (value == Script::MERO) { return "MERO"; }
    if (value == Script::PLRD) { return "PLRD"; }
    if (value == Script::SHRD) { return "SHRD"; }
    if (value == Script::SORA) { return "SORA"; }
    if (value == Script::TAKR) { return "TAKR"; }
    if (value == Script::AGHB) { return "AGHB"; }
    if (value == Script::BASS) { return "BASS"; }
    if (value == Script::DUPL) { return "DUPL"; }
    if (value == Script::ELBA) { return "ELBA"; }
    if (value == Script::GRAN) { return "GRAN"; }
    if (value == Script::HMNG) { return "HMNG"; }
    if (value == Script::KHOJ) { return "KHOJ"; }
    if (value == Script::LINA) { return "LINA"; }
    if (value == Script::MAHJ) { return "MAHJ"; }
    if (value == Script::MANI) { return "MANI"; }
    if (value == Script::MEND) { return "MEND"; }
    if (value == Script::MODI) { return "MODI"; }
    if (value == Script::MROO) { return "MROO"; }
    if (value == Script::NARB) { return "NARB"; }
    if (value == Script::NBAT) { return "NBAT"; }
    if (value == Script::PALM) { return "PALM"; }
    if (value == Script::PAUC) { return "PAUC"; }
    if (value == Script::PERM) { return "PERM"; }
    if (value == Script::PHLP) { return "PHLP"; }
    if (value == Script::SIDD) { return "SIDD"; }
    if (value == Script::SIND) { return "SIND"; }
    if (value == Script::TIRH) { return "TIRH"; }
    if (value == Script::WARA) { return "WARA"; }
    if (value == Script::AHOM) { return "AHOM"; }
    if (value == Script::HATR) { return "HATR"; }
    if (value == Script::HLUW) { return "HLUW"; }
    if (value == Script::HUNG) { return "HUNG"; }
    if (value == Script::MULT) { return "MULT"; }
    if (value == Script::SGNW) { return "SGNW"; }
    if (value == Script::ADLM) { return "ADLM"; }
    if (value == Script::BHKS) { return "BHKS"; }
    if (value == Script::MARC) { return "MARC"; }
    if (value == Script::NEWA) { return "NEWA"; }
    if (value == Script::OSGE) { return "OSGE"; }
    if (value == Script::TANG) { return "TANG"; }
    if (value == Script::GONM) { return "GONM"; }
    if (value == Script::NSHU) { return "NSHU"; }
    if (value == Script::SOYO) { return "SOYO"; }
    if (value == Script::ZANB) { return "ZANB"; }
    if (value == Script::DOGR) { return "DOGR"; }
    if (value == Script::GONG) { return "GONG"; }
    if (value == Script::MAKA) { return "MAKA"; }
    if (value == Script::MEDF) { return "MEDF"; }
    if (value == Script::ROHG) { return "ROHG"; }
    if (value == Script::SOGD) { return "SOGD"; }
    if (value == Script::SOGO) { return "SOGO"; }
    if (value == Script::ELYM) { return "ELYM"; }
    if (value == Script::HMNP) { return "HMNP"; }
    if (value == Script::NAND) { return "NAND"; }
    if (value == Script::WCHO) { return "WCHO"; }
    if (value == Script::CHRS) { return "CHRS"; }
    if (value == Script::DIAK) { return "DIAK"; }
    if (value == Script::KITS) { return "KITS"; }
    if (value == Script::YEZI) { return "YEZI"; }
    if (value == Script::CPMN) { return "CPMN"; }
    if (value == Script::OUGR) { return "OUGR"; }
    if (value == Script::TNSA) { return "TNSA"; }
    if (value == Script::TOTO) { return "TOTO"; }
    if (value == Script::VITH) { return "VITH"; }
    if (value == Script::KAWI) { return "KAWI"; }
    if (value == Script::NAGM) { return "NAGM"; }
    return "NIL";
}


constexpr std::string ToString(Script value) {
    if (value == Script::ZINH) { return "Inherited"; }
    if (value == Script::ZYYY) { return "Common"; }
    if (value == Script::ZZZZ) { return "Unknown"; }
    if (value == Script::ARAB) { return "Arabic"; }
    if (value == Script::ARMN) { return "Armenian"; }
    if (value == Script::BENG) { return "Bengali"; }
    if (value == Script::BOPO) { return "Bopomofo"; }
    if (value == Script::CYRL) { return "Cyrillic"; }
    if (value == Script::DEVA) { return "Devanagari"; }
    if (value == Script::GEOR) { return "Georgian"; }
    if (value == Script::GREK) { return "Greek"; }
    if (value == Script::GUJR) { return "Gujarati"; }
    if (value == Script::GURU) { return "Gurmukhi"; }
    if (value == Script::HANG) { return "Hangul"; }
    if (value == Script::HANI) { return "Han"; }
    if (value == Script::HEBR) { return "Hebrew"; }
    if (value == Script::HIRA) { return "Hiragana"; }
    if (value == Script::KANA) { return "Katakana"; }
    if (value == Script::KNDA) { return "Kannada"; }
    if (value == Script::LAOO) { return "Lao"; }
    if (value == Script::LATN) { return "Latin"; }
    if (value == Script::MLYM) { return "Malayalam"; }
    if (value == Script::ORYA) { return "Oriya"; }
    if (value == Script::TAML) { return "Tamil"; }
    if (value == Script::TELU) { return "Telugu"; }
    if (value == Script::THAI) { return "Thai"; }
    if (value == Script::TIBT) { return "Tibetan"; }
    if (value == Script::BRAI) { return "Braille"; }
    if (value == Script::CANS) { return "Canadian_Aboriginal"; }
    if (value == Script::CHER) { return "Cherokee"; }
    if (value == Script::ETHI) { return "Ethiopic"; }
    if (value == Script::KHMR) { return "Khmer"; }
    if (value == Script::MONG) { return "Mongolian"; }
    if (value == Script::MYMR) { return "Myanmar"; }
    if (value == Script::OGAM) { return "Ogham"; }
    if (value == Script::RUNR) { return "Runic"; }
    if (value == Script::SINH) { return "Sinhala"; }
    if (value == Script::SYRC) { return "Syriac"; }
    if (value == Script::THAA) { return "Thaana"; }
    if (value == Script::YIII) { return "Yi"; }
    if (value == Script::DSRT) { return "Deseret"; }
    if (value == Script::GOTH) { return "Gothic"; }
    if (value == Script::ITAL) { return "Old_Italic"; }
    if (value == Script::BUHD) { return "Buhid"; }
    if (value == Script::HANO) { return "Hanunoo"; }
    if (value == Script::TAGB) { return "Tagbanwa"; }
    if (value == Script::TGLG) { return "Tagalog"; }
    if (value == Script::CPRT) { return "Cypriot"; }
    if (value == Script::LIMB) { return "Limbu"; }
    if (value == Script::LINB) { return "Linear_B"; }
    if (value == Script::OSMA) { return "Osmanya"; }
    if (value == Script::SHAW) { return "Shavian"; }
    if (value == Script::TALE) { return "Tai_Le"; }
    if (value == Script::UGAR) { return "Ugaritic"; }
    if (value == Script::BUGI) { return "Buginese"; }
    if (value == Script::COPT) { return "Coptic"; }
    if (value == Script::GLAG) { return "Glagolitic"; }
    if (value == Script::KHAR) { return "Kharoshthi"; }
    if (value == Script::SYLO) { return "Syloti_Nagri"; }
    if (value == Script::TALU) { return "New_Tai_Lue"; }
    if (value == Script::TFNG) { return "Tifinagh"; }
    if (value == Script::XPEO) { return "Old_Persian"; }
    if (value == Script::BALI) { return "Balinese"; }
    if (value == Script::NKOO) { return "Nko"; }
    if (value == Script::PHAG) { return "Phags_Pa"; }
    if (value == Script::PHNX) { return "Phoenician"; }
    if (value == Script::XSUX) { return "Cuneiform"; }
    if (value == Script::CARI) { return "Carian"; }
    if (value == Script::CHAM) { return "Cham"; }
    if (value == Script::KALI) { return "Kayah_Li"; }
    if (value == Script::LEPC) { return "Lepcha"; }
    if (value == Script::LYCI) { return "Lycian"; }
    if (value == Script::LYDI) { return "Lydian"; }
    if (value == Script::OLCK) { return "Ol_Chiki"; }
    if (value == Script::RJNG) { return "Rejang"; }
    if (value == Script::SAUR) { return "Saurashtra"; }
    if (value == Script::SUND) { return "Sundanese"; }
    if (value == Script::VAII) { return "Vai"; }
    if (value == Script::ARMI) { return "Imperial_Aramaic"; }
    if (value == Script::AVST) { return "Avestan"; }
    if (value == Script::BAMU) { return "Bamum"; }
    if (value == Script::EGYP) { return "Egyptian_Hieroglyphs"; }
    if (value == Script::JAVA) { return "Javanese"; }
    if (value == Script::KTHI) { return "Kaithi"; }
    if (value == Script::LANA) { return "Tai_Tham"; }
    if (value == Script::LISU) { return "Lisu"; }
    if (value == Script::MTEI) { return "Meetei_Mayek"; }
    if (value == Script::ORKH) { return "Old_Turkic"; }
    if (value == Script::PHLI) { return "Inscriptional_Pahlavi"; }
    if (value == Script::PRTI) { return "Inscriptional_Parthian"; }
    if (value == Script::SAMR) { return "Samaritan"; }
    if (value == Script::SARB) { return "Old_South_Arabian"; }
    if (value == Script::TAVT) { return "Tai_Viet"; }
    if (value == Script::BATK) { return "Batak"; }
    if (value == Script::BRAH) { return "Brahmi"; }
    if (value == Script::MAND) { return "Mandaic"; }
    if (value == Script::CAKM) { return "Chakma"; }
    if (value == Script::MERC) { return "Meroitic_Cursive"; }
    if (value == Script::MERO) { return "Meroitic_Hieroglyphs"; }
    if (value == Script::PLRD) { return "Miao"; }
    if (value == Script::SHRD) { return "Sharada"; }
    if (value == Script::SORA) { return "Sora_Sompeng"; }
    if (value == Script::TAKR) { return "Takri"; }
    if (value == Script::AGHB) { return "Caucasian_Albanian"; }
    if (value == Script::BASS) { return "Bassa_Vah"; }
    if (value == Script::DUPL) { return "Duployan"; }
    if (value == Script::ELBA) { return "Elbasan"; }
    if (value == Script::GRAN) { return "Grantha"; }
    if (value == Script::HMNG) { return "Pahawh_Hmong"; }
    if (value == Script::KHOJ) { return "Khojki"; }
    if (value == Script::LINA) { return "Linear_A"; }
    if (value == Script::MAHJ) { return "Mahajani"; }
    if (value == Script::MANI) { return "Manichaean"; }
    if (value == Script::MEND) { return "Mende_Kikakui"; }
    if (value == Script::MODI) { return "Modi"; }
    if (value == Script::MROO) { return "Mro"; }
    if (value == Script::NARB) { return "Old_North_Arabian"; }
    if (value == Script::NBAT) { return "Nabataean"; }
    if (value == Script::PALM) { return "Palmyrene"; }
    if (value == Script::PAUC) { return "Pau_Cin_Hau"; }
    if (value == Script::PERM) { return "Old_Permic"; }
    if (value == Script::PHLP) { return "Psalter_Pahlavi"; }
    if (value == Script::SIDD) { return "Siddham"; }
    if (value == Script::SIND) { return "Khudawadi"; }
    if (value == Script::TIRH) { return "Tirhuta"; }
    if (value == Script::WARA) { return "Warang_Citi"; }
    if (value == Script::AHOM) { return "Ahom"; }
    if (value == Script::HATR) { return "Hatran"; }
    if (value == Script::HLUW) { return "Anatolian_Hieroglyphs"; }
    if (value == Script::HUNG) { return "Old_Hungarian"; }
    if (value == Script::MULT) { return "Multani"; }
    if (value == Script::SGNW) { return "SignWriting"; }
    if (value == Script::ADLM) { return "Adlam"; }
    if (value == Script::BHKS) { return "Bhaiksuki"; }
    if (value == Script::MARC) { return "Marchen"; }
    if (value == Script::NEWA) { return "Newa"; }
    if (value == Script::OSGE) { return "Osage"; }
    if (value == Script::TANG) { return "Tangut"; }
    if (value == Script::GONM) { return "Masaram_Gondi"; }
    if (value == Script::NSHU) { return "Nushu"; }
    if (value == Script::SOYO) { return "Soyombo"; }
    if (value == Script::ZANB) { return "Zanabazar_Square"; }
    if (value == Script::DOGR) { return "Dogra"; }
    if (value == Script::GONG) { return "Gunjala_Gondi"; }
    if (value == Script::MAKA) { return "Makasar"; }
    if (value == Script::MEDF) { return "Medefaidrin"; }
    if (value == Script::ROHG) { return "Hanifi_Rohingya"; }
    if (value == Script::SOGD) { return "Sogdian"; }
    if (value == Script::SOGO) { return "Old_Sogdian"; }
    if (value == Script::ELYM) { return "Elymaic"; }
    if (value == Script::HMNP) { return "Nyiakeng_Puachue_Hmong"; }
    if (value == Script::NAND) { return "Nandinagari"; }
    if (value == Script::WCHO) { return "Wancho"; }
    if (value == Script::CHRS) { return "Chorasmian"; }
    if (value == Script::DIAK) { return "Dives_Akuru"; }
    if (value == Script::KITS) { return "Khitan_Small_Script"; }
    if (value == Script::YEZI) { return "Yezidi"; }
    if (value == Script::CPMN) { return "Cypro_Minoan"; }
    if (value == Script::OUGR) { return "Old_Uyghur"; }
    if (value == Script::TNSA) { return "Tangsa"; }
    if (value == Script::TOTO) { return "Toto"; }
    if (value == Script::VITH) { return "Vithkuqi"; }
    if (value == Script::KAWI) { return "Kawi"; }
    if (value == Script::NAGM) { return "Nag_Mundari"; }
    return "NIL";
}


}
