// Copyright © 2024 Jason Stredwick

/***
 * TODO: Figure out how to convert these mapping functions to something other than repeated if statements.
 */

#pragma once


#include <string>
#include <string_view>

#include "jcu/script.hpp"


namespace jcu::strings::script {


constexpr jcu::Script FromAliasString(std::string_view sv) {
    if (sv == std::string_view{"ZINH"}) { return jcu::Script::ZINH; }
    if (sv == std::string_view{"ZYYY"}) { return jcu::Script::ZYYY; }
    if (sv == std::string_view{"ZZZZ"}) { return jcu::Script::ZZZZ; }
    if (sv == std::string_view{"ARAB"}) { return jcu::Script::ARAB; }
    if (sv == std::string_view{"ARMN"}) { return jcu::Script::ARMN; }
    if (sv == std::string_view{"BENG"}) { return jcu::Script::BENG; }
    if (sv == std::string_view{"BOPO"}) { return jcu::Script::BOPO; }
    if (sv == std::string_view{"CYRL"}) { return jcu::Script::CYRL; }
    if (sv == std::string_view{"DEVA"}) { return jcu::Script::DEVA; }
    if (sv == std::string_view{"GEOR"}) { return jcu::Script::GEOR; }
    if (sv == std::string_view{"GREK"}) { return jcu::Script::GREK; }
    if (sv == std::string_view{"GUJR"}) { return jcu::Script::GUJR; }
    if (sv == std::string_view{"GURU"}) { return jcu::Script::GURU; }
    if (sv == std::string_view{"HANG"}) { return jcu::Script::HANG; }
    if (sv == std::string_view{"HANI"}) { return jcu::Script::HANI; }
    if (sv == std::string_view{"HEBR"}) { return jcu::Script::HEBR; }
    if (sv == std::string_view{"HIRA"}) { return jcu::Script::HIRA; }
    if (sv == std::string_view{"KANA"}) { return jcu::Script::KANA; }
    if (sv == std::string_view{"KNDA"}) { return jcu::Script::KNDA; }
    if (sv == std::string_view{"LAOO"}) { return jcu::Script::LAOO; }
    if (sv == std::string_view{"LATN"}) { return jcu::Script::LATN; }
    if (sv == std::string_view{"MLYM"}) { return jcu::Script::MLYM; }
    if (sv == std::string_view{"ORYA"}) { return jcu::Script::ORYA; }
    if (sv == std::string_view{"TAML"}) { return jcu::Script::TAML; }
    if (sv == std::string_view{"TELU"}) { return jcu::Script::TELU; }
    if (sv == std::string_view{"THAI"}) { return jcu::Script::THAI; }
    if (sv == std::string_view{"TIBT"}) { return jcu::Script::TIBT; }
    if (sv == std::string_view{"BRAI"}) { return jcu::Script::BRAI; }
    if (sv == std::string_view{"CANS"}) { return jcu::Script::CANS; }
    if (sv == std::string_view{"CHER"}) { return jcu::Script::CHER; }
    if (sv == std::string_view{"ETHI"}) { return jcu::Script::ETHI; }
    if (sv == std::string_view{"KHMR"}) { return jcu::Script::KHMR; }
    if (sv == std::string_view{"MONG"}) { return jcu::Script::MONG; }
    if (sv == std::string_view{"MYMR"}) { return jcu::Script::MYMR; }
    if (sv == std::string_view{"OGAM"}) { return jcu::Script::OGAM; }
    if (sv == std::string_view{"RUNR"}) { return jcu::Script::RUNR; }
    if (sv == std::string_view{"SINH"}) { return jcu::Script::SINH; }
    if (sv == std::string_view{"SYRC"}) { return jcu::Script::SYRC; }
    if (sv == std::string_view{"THAA"}) { return jcu::Script::THAA; }
    if (sv == std::string_view{"YIII"}) { return jcu::Script::YIII; }
    if (sv == std::string_view{"DSRT"}) { return jcu::Script::DSRT; }
    if (sv == std::string_view{"GOTH"}) { return jcu::Script::GOTH; }
    if (sv == std::string_view{"ITAL"}) { return jcu::Script::ITAL; }
    if (sv == std::string_view{"BUHD"}) { return jcu::Script::BUHD; }
    if (sv == std::string_view{"HANO"}) { return jcu::Script::HANO; }
    if (sv == std::string_view{"TAGB"}) { return jcu::Script::TAGB; }
    if (sv == std::string_view{"TGLG"}) { return jcu::Script::TGLG; }
    if (sv == std::string_view{"CPRT"}) { return jcu::Script::CPRT; }
    if (sv == std::string_view{"LIMB"}) { return jcu::Script::LIMB; }
    if (sv == std::string_view{"LINB"}) { return jcu::Script::LINB; }
    if (sv == std::string_view{"OSMA"}) { return jcu::Script::OSMA; }
    if (sv == std::string_view{"SHAW"}) { return jcu::Script::SHAW; }
    if (sv == std::string_view{"TALE"}) { return jcu::Script::TALE; }
    if (sv == std::string_view{"UGAR"}) { return jcu::Script::UGAR; }
    if (sv == std::string_view{"BUGI"}) { return jcu::Script::BUGI; }
    if (sv == std::string_view{"COPT"}) { return jcu::Script::COPT; }
    if (sv == std::string_view{"GLAG"}) { return jcu::Script::GLAG; }
    if (sv == std::string_view{"KHAR"}) { return jcu::Script::KHAR; }
    if (sv == std::string_view{"SYLO"}) { return jcu::Script::SYLO; }
    if (sv == std::string_view{"TALU"}) { return jcu::Script::TALU; }
    if (sv == std::string_view{"TFNG"}) { return jcu::Script::TFNG; }
    if (sv == std::string_view{"XPEO"}) { return jcu::Script::XPEO; }
    if (sv == std::string_view{"BALI"}) { return jcu::Script::BALI; }
    if (sv == std::string_view{"NKOO"}) { return jcu::Script::NKOO; }
    if (sv == std::string_view{"PHAG"}) { return jcu::Script::PHAG; }
    if (sv == std::string_view{"PHNX"}) { return jcu::Script::PHNX; }
    if (sv == std::string_view{"XSUX"}) { return jcu::Script::XSUX; }
    if (sv == std::string_view{"CARI"}) { return jcu::Script::CARI; }
    if (sv == std::string_view{"CHAM"}) { return jcu::Script::CHAM; }
    if (sv == std::string_view{"KALI"}) { return jcu::Script::KALI; }
    if (sv == std::string_view{"LEPC"}) { return jcu::Script::LEPC; }
    if (sv == std::string_view{"LYCI"}) { return jcu::Script::LYCI; }
    if (sv == std::string_view{"LYDI"}) { return jcu::Script::LYDI; }
    if (sv == std::string_view{"OLCK"}) { return jcu::Script::OLCK; }
    if (sv == std::string_view{"RJNG"}) { return jcu::Script::RJNG; }
    if (sv == std::string_view{"SAUR"}) { return jcu::Script::SAUR; }
    if (sv == std::string_view{"SUND"}) { return jcu::Script::SUND; }
    if (sv == std::string_view{"VAII"}) { return jcu::Script::VAII; }
    if (sv == std::string_view{"ARMI"}) { return jcu::Script::ARMI; }
    if (sv == std::string_view{"AVST"}) { return jcu::Script::AVST; }
    if (sv == std::string_view{"BAMU"}) { return jcu::Script::BAMU; }
    if (sv == std::string_view{"EGYP"}) { return jcu::Script::EGYP; }
    if (sv == std::string_view{"JAVA"}) { return jcu::Script::JAVA; }
    if (sv == std::string_view{"KTHI"}) { return jcu::Script::KTHI; }
    if (sv == std::string_view{"LANA"}) { return jcu::Script::LANA; }
    if (sv == std::string_view{"LISU"}) { return jcu::Script::LISU; }
    if (sv == std::string_view{"MTEI"}) { return jcu::Script::MTEI; }
    if (sv == std::string_view{"ORKH"}) { return jcu::Script::ORKH; }
    if (sv == std::string_view{"PHLI"}) { return jcu::Script::PHLI; }
    if (sv == std::string_view{"PRTI"}) { return jcu::Script::PRTI; }
    if (sv == std::string_view{"SAMR"}) { return jcu::Script::SAMR; }
    if (sv == std::string_view{"SARB"}) { return jcu::Script::SARB; }
    if (sv == std::string_view{"TAVT"}) { return jcu::Script::TAVT; }
    if (sv == std::string_view{"BATK"}) { return jcu::Script::BATK; }
    if (sv == std::string_view{"BRAH"}) { return jcu::Script::BRAH; }
    if (sv == std::string_view{"MAND"}) { return jcu::Script::MAND; }
    if (sv == std::string_view{"CAKM"}) { return jcu::Script::CAKM; }
    if (sv == std::string_view{"MERC"}) { return jcu::Script::MERC; }
    if (sv == std::string_view{"MERO"}) { return jcu::Script::MERO; }
    if (sv == std::string_view{"PLRD"}) { return jcu::Script::PLRD; }
    if (sv == std::string_view{"SHRD"}) { return jcu::Script::SHRD; }
    if (sv == std::string_view{"SORA"}) { return jcu::Script::SORA; }
    if (sv == std::string_view{"TAKR"}) { return jcu::Script::TAKR; }
    if (sv == std::string_view{"AGHB"}) { return jcu::Script::AGHB; }
    if (sv == std::string_view{"BASS"}) { return jcu::Script::BASS; }
    if (sv == std::string_view{"DUPL"}) { return jcu::Script::DUPL; }
    if (sv == std::string_view{"ELBA"}) { return jcu::Script::ELBA; }
    if (sv == std::string_view{"GRAN"}) { return jcu::Script::GRAN; }
    if (sv == std::string_view{"HMNG"}) { return jcu::Script::HMNG; }
    if (sv == std::string_view{"KHOJ"}) { return jcu::Script::KHOJ; }
    if (sv == std::string_view{"LINA"}) { return jcu::Script::LINA; }
    if (sv == std::string_view{"MAHJ"}) { return jcu::Script::MAHJ; }
    if (sv == std::string_view{"MANI"}) { return jcu::Script::MANI; }
    if (sv == std::string_view{"MEND"}) { return jcu::Script::MEND; }
    if (sv == std::string_view{"MODI"}) { return jcu::Script::MODI; }
    if (sv == std::string_view{"MROO"}) { return jcu::Script::MROO; }
    if (sv == std::string_view{"NARB"}) { return jcu::Script::NARB; }
    if (sv == std::string_view{"NBAT"}) { return jcu::Script::NBAT; }
    if (sv == std::string_view{"PALM"}) { return jcu::Script::PALM; }
    if (sv == std::string_view{"PAUC"}) { return jcu::Script::PAUC; }
    if (sv == std::string_view{"PERM"}) { return jcu::Script::PERM; }
    if (sv == std::string_view{"PHLP"}) { return jcu::Script::PHLP; }
    if (sv == std::string_view{"SIDD"}) { return jcu::Script::SIDD; }
    if (sv == std::string_view{"SIND"}) { return jcu::Script::SIND; }
    if (sv == std::string_view{"TIRH"}) { return jcu::Script::TIRH; }
    if (sv == std::string_view{"WARA"}) { return jcu::Script::WARA; }
    if (sv == std::string_view{"AHOM"}) { return jcu::Script::AHOM; }
    if (sv == std::string_view{"HATR"}) { return jcu::Script::HATR; }
    if (sv == std::string_view{"HLUW"}) { return jcu::Script::HLUW; }
    if (sv == std::string_view{"HUNG"}) { return jcu::Script::HUNG; }
    if (sv == std::string_view{"MULT"}) { return jcu::Script::MULT; }
    if (sv == std::string_view{"SGNW"}) { return jcu::Script::SGNW; }
    if (sv == std::string_view{"ADLM"}) { return jcu::Script::ADLM; }
    if (sv == std::string_view{"BHKS"}) { return jcu::Script::BHKS; }
    if (sv == std::string_view{"MARC"}) { return jcu::Script::MARC; }
    if (sv == std::string_view{"NEWA"}) { return jcu::Script::NEWA; }
    if (sv == std::string_view{"OSGE"}) { return jcu::Script::OSGE; }
    if (sv == std::string_view{"TANG"}) { return jcu::Script::TANG; }
    if (sv == std::string_view{"GONM"}) { return jcu::Script::GONM; }
    if (sv == std::string_view{"NSHU"}) { return jcu::Script::NSHU; }
    if (sv == std::string_view{"SOYO"}) { return jcu::Script::SOYO; }
    if (sv == std::string_view{"ZANB"}) { return jcu::Script::ZANB; }
    if (sv == std::string_view{"DOGR"}) { return jcu::Script::DOGR; }
    if (sv == std::string_view{"GONG"}) { return jcu::Script::GONG; }
    if (sv == std::string_view{"MAKA"}) { return jcu::Script::MAKA; }
    if (sv == std::string_view{"MEDF"}) { return jcu::Script::MEDF; }
    if (sv == std::string_view{"ROHG"}) { return jcu::Script::ROHG; }
    if (sv == std::string_view{"SOGD"}) { return jcu::Script::SOGD; }
    if (sv == std::string_view{"SOGO"}) { return jcu::Script::SOGO; }
    if (sv == std::string_view{"ELYM"}) { return jcu::Script::ELYM; }
    if (sv == std::string_view{"HMNP"}) { return jcu::Script::HMNP; }
    if (sv == std::string_view{"NAND"}) { return jcu::Script::NAND; }
    if (sv == std::string_view{"WCHO"}) { return jcu::Script::WCHO; }
    if (sv == std::string_view{"CHRS"}) { return jcu::Script::CHRS; }
    if (sv == std::string_view{"DIAK"}) { return jcu::Script::DIAK; }
    if (sv == std::string_view{"KITS"}) { return jcu::Script::KITS; }
    if (sv == std::string_view{"YEZI"}) { return jcu::Script::YEZI; }
    if (sv == std::string_view{"CPMN"}) { return jcu::Script::CPMN; }
    if (sv == std::string_view{"OUGR"}) { return jcu::Script::OUGR; }
    if (sv == std::string_view{"TNSA"}) { return jcu::Script::TNSA; }
    if (sv == std::string_view{"TOTO"}) { return jcu::Script::TOTO; }
    if (sv == std::string_view{"VITH"}) { return jcu::Script::VITH; }
    if (sv == std::string_view{"KAWI"}) { return jcu::Script::KAWI; }
    if (sv == std::string_view{"NAGM"}) { return jcu::Script::NAGM; }
    if (sv == std::string_view{"GARA"}) { return jcu::Script::GARA; }
    if (sv == std::string_view{"GUKH"}) { return jcu::Script::GUKH; }
    if (sv == std::string_view{"KRAI"}) { return jcu::Script::KRAI; }
    if (sv == std::string_view{"ONAO"}) { return jcu::Script::ONAO; }
    if (sv == std::string_view{"SUNU"}) { return jcu::Script::SUNU; }
    if (sv == std::string_view{"TODR"}) { return jcu::Script::TODR; }
    if (sv == std::string_view{"TUTG"}) { return jcu::Script::TUTG; }
    return jcu::Script::NIL;
}


constexpr jcu::Script FromString(std::string_view sv) {
    if (sv == std::string_view{"Inherited"}) { return jcu::Script::ZINH; }
    if (sv == std::string_view{"Common"}) { return jcu::Script::ZYYY; }
    if (sv == std::string_view{"Unknown"}) { return jcu::Script::ZZZZ; }
    if (sv == std::string_view{"Arabic"}) { return jcu::Script::ARAB; }
    if (sv == std::string_view{"Armenian"}) { return jcu::Script::ARMN; }
    if (sv == std::string_view{"Bengali"}) { return jcu::Script::BENG; }
    if (sv == std::string_view{"Bopomofo"}) { return jcu::Script::BOPO; }
    if (sv == std::string_view{"Cyrillic"}) { return jcu::Script::CYRL; }
    if (sv == std::string_view{"Devanagari"}) { return jcu::Script::DEVA; }
    if (sv == std::string_view{"Georgian"}) { return jcu::Script::GEOR; }
    if (sv == std::string_view{"Greek"}) { return jcu::Script::GREK; }
    if (sv == std::string_view{"Gujarati"}) { return jcu::Script::GUJR; }
    if (sv == std::string_view{"Gurmukhi"}) { return jcu::Script::GURU; }
    if (sv == std::string_view{"Hangul"}) { return jcu::Script::HANG; }
    if (sv == std::string_view{"Han"}) { return jcu::Script::HANI; }
    if (sv == std::string_view{"Hebrew"}) { return jcu::Script::HEBR; }
    if (sv == std::string_view{"Hiragana"}) { return jcu::Script::HIRA; }
    if (sv == std::string_view{"Katakana"}) { return jcu::Script::KANA; }
    if (sv == std::string_view{"Kannada"}) { return jcu::Script::KNDA; }
    if (sv == std::string_view{"Lao"}) { return jcu::Script::LAOO; }
    if (sv == std::string_view{"Latin"}) { return jcu::Script::LATN; }
    if (sv == std::string_view{"Malayalam"}) { return jcu::Script::MLYM; }
    if (sv == std::string_view{"Oriya"}) { return jcu::Script::ORYA; }
    if (sv == std::string_view{"Tamil"}) { return jcu::Script::TAML; }
    if (sv == std::string_view{"Telugu"}) { return jcu::Script::TELU; }
    if (sv == std::string_view{"Thai"}) { return jcu::Script::THAI; }
    if (sv == std::string_view{"Tibetan"}) { return jcu::Script::TIBT; }
    if (sv == std::string_view{"Braille"}) { return jcu::Script::BRAI; }
    if (sv == std::string_view{"Canadian_Aboriginal"}) { return jcu::Script::CANS; }
    if (sv == std::string_view{"Cherokee"}) { return jcu::Script::CHER; }
    if (sv == std::string_view{"Ethiopic"}) { return jcu::Script::ETHI; }
    if (sv == std::string_view{"Khmer"}) { return jcu::Script::KHMR; }
    if (sv == std::string_view{"Mongolian"}) { return jcu::Script::MONG; }
    if (sv == std::string_view{"Myanmar"}) { return jcu::Script::MYMR; }
    if (sv == std::string_view{"Ogham"}) { return jcu::Script::OGAM; }
    if (sv == std::string_view{"Runic"}) { return jcu::Script::RUNR; }
    if (sv == std::string_view{"Sinhala"}) { return jcu::Script::SINH; }
    if (sv == std::string_view{"Syriac"}) { return jcu::Script::SYRC; }
    if (sv == std::string_view{"Thaana"}) { return jcu::Script::THAA; }
    if (sv == std::string_view{"Yi"}) { return jcu::Script::YIII; }
    if (sv == std::string_view{"Deseret"}) { return jcu::Script::DSRT; }
    if (sv == std::string_view{"Gothic"}) { return jcu::Script::GOTH; }
    if (sv == std::string_view{"Old_Italic"}) { return jcu::Script::ITAL; }
    if (sv == std::string_view{"Buhid"}) { return jcu::Script::BUHD; }
    if (sv == std::string_view{"Hanunoo"}) { return jcu::Script::HANO; }
    if (sv == std::string_view{"Tagbanwa"}) { return jcu::Script::TAGB; }
    if (sv == std::string_view{"Tagalog"}) { return jcu::Script::TGLG; }
    if (sv == std::string_view{"Cypriot"}) { return jcu::Script::CPRT; }
    if (sv == std::string_view{"Limbu"}) { return jcu::Script::LIMB; }
    if (sv == std::string_view{"Linear_B"}) { return jcu::Script::LINB; }
    if (sv == std::string_view{"Osmanya"}) { return jcu::Script::OSMA; }
    if (sv == std::string_view{"Shavian"}) { return jcu::Script::SHAW; }
    if (sv == std::string_view{"Tai_Le"}) { return jcu::Script::TALE; }
    if (sv == std::string_view{"Ugaritic"}) { return jcu::Script::UGAR; }
    if (sv == std::string_view{"Buginese"}) { return jcu::Script::BUGI; }
    if (sv == std::string_view{"Coptic"}) { return jcu::Script::COPT; }
    if (sv == std::string_view{"Glagolitic"}) { return jcu::Script::GLAG; }
    if (sv == std::string_view{"Kharoshthi"}) { return jcu::Script::KHAR; }
    if (sv == std::string_view{"Syloti_Nagri"}) { return jcu::Script::SYLO; }
    if (sv == std::string_view{"New_Tai_Lue"}) { return jcu::Script::TALU; }
    if (sv == std::string_view{"Tifinagh"}) { return jcu::Script::TFNG; }
    if (sv == std::string_view{"Old_Persian"}) { return jcu::Script::XPEO; }
    if (sv == std::string_view{"Balinese"}) { return jcu::Script::BALI; }
    if (sv == std::string_view{"Nko"}) { return jcu::Script::NKOO; }
    if (sv == std::string_view{"Phags_Pa"}) { return jcu::Script::PHAG; }
    if (sv == std::string_view{"Phoenician"}) { return jcu::Script::PHNX; }
    if (sv == std::string_view{"Cuneiform"}) { return jcu::Script::XSUX; }
    if (sv == std::string_view{"Carian"}) { return jcu::Script::CARI; }
    if (sv == std::string_view{"Cham"}) { return jcu::Script::CHAM; }
    if (sv == std::string_view{"Kayah_Li"}) { return jcu::Script::KALI; }
    if (sv == std::string_view{"Lepcha"}) { return jcu::Script::LEPC; }
    if (sv == std::string_view{"Lycian"}) { return jcu::Script::LYCI; }
    if (sv == std::string_view{"Lydian"}) { return jcu::Script::LYDI; }
    if (sv == std::string_view{"Ol_Chiki"}) { return jcu::Script::OLCK; }
    if (sv == std::string_view{"Rejang"}) { return jcu::Script::RJNG; }
    if (sv == std::string_view{"Saurashtra"}) { return jcu::Script::SAUR; }
    if (sv == std::string_view{"Sundanese"}) { return jcu::Script::SUND; }
    if (sv == std::string_view{"Vai"}) { return jcu::Script::VAII; }
    if (sv == std::string_view{"Imperial_Aramaic"}) { return jcu::Script::ARMI; }
    if (sv == std::string_view{"Avestan"}) { return jcu::Script::AVST; }
    if (sv == std::string_view{"Bamum"}) { return jcu::Script::BAMU; }
    if (sv == std::string_view{"Egyptian_Hieroglyphs"}) { return jcu::Script::EGYP; }
    if (sv == std::string_view{"Javanese"}) { return jcu::Script::JAVA; }
    if (sv == std::string_view{"Kaithi"}) { return jcu::Script::KTHI; }
    if (sv == std::string_view{"Tai_Tham"}) { return jcu::Script::LANA; }
    if (sv == std::string_view{"Lisu"}) { return jcu::Script::LISU; }
    if (sv == std::string_view{"Meetei_Mayek"}) { return jcu::Script::MTEI; }
    if (sv == std::string_view{"Old_Turkic"}) { return jcu::Script::ORKH; }
    if (sv == std::string_view{"Inscriptional_Pahlavi"}) { return jcu::Script::PHLI; }
    if (sv == std::string_view{"Inscriptional_Parthian"}) { return jcu::Script::PRTI; }
    if (sv == std::string_view{"Samaritan"}) { return jcu::Script::SAMR; }
    if (sv == std::string_view{"Old_South_Arabian"}) { return jcu::Script::SARB; }
    if (sv == std::string_view{"Tai_Viet"}) { return jcu::Script::TAVT; }
    if (sv == std::string_view{"Batak"}) { return jcu::Script::BATK; }
    if (sv == std::string_view{"Brahmi"}) { return jcu::Script::BRAH; }
    if (sv == std::string_view{"Mandaic"}) { return jcu::Script::MAND; }
    if (sv == std::string_view{"Chakma"}) { return jcu::Script::CAKM; }
    if (sv == std::string_view{"Meroitic_Cursive"}) { return jcu::Script::MERC; }
    if (sv == std::string_view{"Meroitic_Hieroglyphs"}) { return jcu::Script::MERO; }
    if (sv == std::string_view{"Miao"}) { return jcu::Script::PLRD; }
    if (sv == std::string_view{"Sharada"}) { return jcu::Script::SHRD; }
    if (sv == std::string_view{"Sora_Sompeng"}) { return jcu::Script::SORA; }
    if (sv == std::string_view{"Takri"}) { return jcu::Script::TAKR; }
    if (sv == std::string_view{"Caucasian_Albanian"}) { return jcu::Script::AGHB; }
    if (sv == std::string_view{"Bassa_Vah"}) { return jcu::Script::BASS; }
    if (sv == std::string_view{"Duployan"}) { return jcu::Script::DUPL; }
    if (sv == std::string_view{"Elbasan"}) { return jcu::Script::ELBA; }
    if (sv == std::string_view{"Grantha"}) { return jcu::Script::GRAN; }
    if (sv == std::string_view{"Pahawh_Hmong"}) { return jcu::Script::HMNG; }
    if (sv == std::string_view{"Khojki"}) { return jcu::Script::KHOJ; }
    if (sv == std::string_view{"Linear_A"}) { return jcu::Script::LINA; }
    if (sv == std::string_view{"Mahajani"}) { return jcu::Script::MAHJ; }
    if (sv == std::string_view{"Manichaean"}) { return jcu::Script::MANI; }
    if (sv == std::string_view{"Mende_Kikakui"}) { return jcu::Script::MEND; }
    if (sv == std::string_view{"Modi"}) { return jcu::Script::MODI; }
    if (sv == std::string_view{"Mro"}) { return jcu::Script::MROO; }
    if (sv == std::string_view{"Old_North_Arabian"}) { return jcu::Script::NARB; }
    if (sv == std::string_view{"Nabataean"}) { return jcu::Script::NBAT; }
    if (sv == std::string_view{"Palmyrene"}) { return jcu::Script::PALM; }
    if (sv == std::string_view{"Pau_Cin_Hau"}) { return jcu::Script::PAUC; }
    if (sv == std::string_view{"Old_Permic"}) { return jcu::Script::PERM; }
    if (sv == std::string_view{"Psalter_Pahlavi"}) { return jcu::Script::PHLP; }
    if (sv == std::string_view{"Siddham"}) { return jcu::Script::SIDD; }
    if (sv == std::string_view{"Khudawadi"}) { return jcu::Script::SIND; }
    if (sv == std::string_view{"Tirhuta"}) { return jcu::Script::TIRH; }
    if (sv == std::string_view{"Warang_Citi"}) { return jcu::Script::WARA; }
    if (sv == std::string_view{"Ahom"}) { return jcu::Script::AHOM; }
    if (sv == std::string_view{"Hatran"}) { return jcu::Script::HATR; }
    if (sv == std::string_view{"Anatolian_Hieroglyphs"}) { return jcu::Script::HLUW; }
    if (sv == std::string_view{"Old_Hungarian"}) { return jcu::Script::HUNG; }
    if (sv == std::string_view{"Multani"}) { return jcu::Script::MULT; }
    if (sv == std::string_view{"SignWriting"}) { return jcu::Script::SGNW; }
    if (sv == std::string_view{"Adlam"}) { return jcu::Script::ADLM; }
    if (sv == std::string_view{"Bhaiksuki"}) { return jcu::Script::BHKS; }
    if (sv == std::string_view{"Marchen"}) { return jcu::Script::MARC; }
    if (sv == std::string_view{"Newa"}) { return jcu::Script::NEWA; }
    if (sv == std::string_view{"Osage"}) { return jcu::Script::OSGE; }
    if (sv == std::string_view{"Tangut"}) { return jcu::Script::TANG; }
    if (sv == std::string_view{"Masaram_Gondi"}) { return jcu::Script::GONM; }
    if (sv == std::string_view{"Nushu"}) { return jcu::Script::NSHU; }
    if (sv == std::string_view{"Soyombo"}) { return jcu::Script::SOYO; }
    if (sv == std::string_view{"Zanabazar_Square"}) { return jcu::Script::ZANB; }
    if (sv == std::string_view{"Dogra"}) { return jcu::Script::DOGR; }
    if (sv == std::string_view{"Gunjala_Gondi"}) { return jcu::Script::GONG; }
    if (sv == std::string_view{"Makasar"}) { return jcu::Script::MAKA; }
    if (sv == std::string_view{"Medefaidrin"}) { return jcu::Script::MEDF; }
    if (sv == std::string_view{"Hanifi_Rohingya"}) { return jcu::Script::ROHG; }
    if (sv == std::string_view{"Sogdian"}) { return jcu::Script::SOGD; }
    if (sv == std::string_view{"Old_Sogdian"}) { return jcu::Script::SOGO; }
    if (sv == std::string_view{"Elymaic"}) { return jcu::Script::ELYM; }
    if (sv == std::string_view{"Nyiakeng_Puachue_Hmong"}) { return jcu::Script::HMNP; }
    if (sv == std::string_view{"Nandinagari"}) { return jcu::Script::NAND; }
    if (sv == std::string_view{"Wancho"}) { return jcu::Script::WCHO; }
    if (sv == std::string_view{"Chorasmian"}) { return jcu::Script::CHRS; }
    if (sv == std::string_view{"Dives_Akuru"}) { return jcu::Script::DIAK; }
    if (sv == std::string_view{"Khitan_Small_jcu::Script"}) { return jcu::Script::KITS; }
    if (sv == std::string_view{"Yezidi"}) { return jcu::Script::YEZI; }
    if (sv == std::string_view{"Cypro_Minoan"}) { return jcu::Script::CPMN; }
    if (sv == std::string_view{"Old_Uyghur"}) { return jcu::Script::OUGR; }
    if (sv == std::string_view{"Tangsa"}) { return jcu::Script::TNSA; }
    if (sv == std::string_view{"Toto"}) { return jcu::Script::TOTO; }
    if (sv == std::string_view{"Vithkuqi"}) { return jcu::Script::VITH; }
    if (sv == std::string_view{"Kawi"}) { return jcu::Script::KAWI; }
    if (sv == std::string_view{"Nag_Mundari"}) { return jcu::Script::NAGM; }
    if (sv == std::string_view{"Garay"}) { return jcu::Script::GARA; }
    if (sv == std::string_view{"Gurung_Khema"}) { return jcu::Script::GUKH; }
    if (sv == std::string_view{"Kirat_Rai"}) { return jcu::Script::KRAI; }
    if (sv == std::string_view{"Ol_Onal"}) { return jcu::Script::ONAO; }
    if (sv == std::string_view{"Sunuwar"}) { return jcu::Script::SUNU; }
    if (sv == std::string_view{"Todhri"}) { return jcu::Script::TODR; }
    if (sv == std::string_view{"Tulu_Tigalari"}) { return jcu::Script::TUTG; }
    return jcu::Script::NIL;
}


constexpr std::string ToAliasString(jcu::Script value) {
    if (value == jcu::Script::ZINH) { return "ZINH"; }
    if (value == jcu::Script::ZYYY) { return "ZYYY"; }
    if (value == jcu::Script::ZZZZ) { return "ZZZZ"; }
    if (value == jcu::Script::ARAB) { return "ARAB"; }
    if (value == jcu::Script::ARMN) { return "ARMN"; }
    if (value == jcu::Script::BENG) { return "BENG"; }
    if (value == jcu::Script::BOPO) { return "BOPO"; }
    if (value == jcu::Script::CYRL) { return "CYRL"; }
    if (value == jcu::Script::DEVA) { return "DEVA"; }
    if (value == jcu::Script::GEOR) { return "GEOR"; }
    if (value == jcu::Script::GREK) { return "GREK"; }
    if (value == jcu::Script::GUJR) { return "GUJR"; }
    if (value == jcu::Script::GURU) { return "GURU"; }
    if (value == jcu::Script::HANG) { return "HANG"; }
    if (value == jcu::Script::HANI) { return "HANI"; }
    if (value == jcu::Script::HEBR) { return "HEBR"; }
    if (value == jcu::Script::HIRA) { return "HIRA"; }
    if (value == jcu::Script::KANA) { return "KANA"; }
    if (value == jcu::Script::KNDA) { return "KNDA"; }
    if (value == jcu::Script::LAOO) { return "LAOO"; }
    if (value == jcu::Script::LATN) { return "LATN"; }
    if (value == jcu::Script::MLYM) { return "MLYM"; }
    if (value == jcu::Script::ORYA) { return "ORYA"; }
    if (value == jcu::Script::TAML) { return "TAML"; }
    if (value == jcu::Script::TELU) { return "TELU"; }
    if (value == jcu::Script::THAI) { return "THAI"; }
    if (value == jcu::Script::TIBT) { return "TIBT"; }
    if (value == jcu::Script::BRAI) { return "BRAI"; }
    if (value == jcu::Script::CANS) { return "CANS"; }
    if (value == jcu::Script::CHER) { return "CHER"; }
    if (value == jcu::Script::ETHI) { return "ETHI"; }
    if (value == jcu::Script::KHMR) { return "KHMR"; }
    if (value == jcu::Script::MONG) { return "MONG"; }
    if (value == jcu::Script::MYMR) { return "MYMR"; }
    if (value == jcu::Script::OGAM) { return "OGAM"; }
    if (value == jcu::Script::RUNR) { return "RUNR"; }
    if (value == jcu::Script::SINH) { return "SINH"; }
    if (value == jcu::Script::SYRC) { return "SYRC"; }
    if (value == jcu::Script::THAA) { return "THAA"; }
    if (value == jcu::Script::YIII) { return "YIII"; }
    if (value == jcu::Script::DSRT) { return "DSRT"; }
    if (value == jcu::Script::GOTH) { return "GOTH"; }
    if (value == jcu::Script::ITAL) { return "ITAL"; }
    if (value == jcu::Script::BUHD) { return "BUHD"; }
    if (value == jcu::Script::HANO) { return "HANO"; }
    if (value == jcu::Script::TAGB) { return "TAGB"; }
    if (value == jcu::Script::TGLG) { return "TGLG"; }
    if (value == jcu::Script::CPRT) { return "CPRT"; }
    if (value == jcu::Script::LIMB) { return "LIMB"; }
    if (value == jcu::Script::LINB) { return "LINB"; }
    if (value == jcu::Script::OSMA) { return "OSMA"; }
    if (value == jcu::Script::SHAW) { return "SHAW"; }
    if (value == jcu::Script::TALE) { return "TALE"; }
    if (value == jcu::Script::UGAR) { return "UGAR"; }
    if (value == jcu::Script::BUGI) { return "BUGI"; }
    if (value == jcu::Script::COPT) { return "COPT"; }
    if (value == jcu::Script::GLAG) { return "GLAG"; }
    if (value == jcu::Script::KHAR) { return "KHAR"; }
    if (value == jcu::Script::SYLO) { return "SYLO"; }
    if (value == jcu::Script::TALU) { return "TALU"; }
    if (value == jcu::Script::TFNG) { return "TFNG"; }
    if (value == jcu::Script::XPEO) { return "XPEO"; }
    if (value == jcu::Script::BALI) { return "BALI"; }
    if (value == jcu::Script::NKOO) { return "NKOO"; }
    if (value == jcu::Script::PHAG) { return "PHAG"; }
    if (value == jcu::Script::PHNX) { return "PHNX"; }
    if (value == jcu::Script::XSUX) { return "XSUX"; }
    if (value == jcu::Script::CARI) { return "CARI"; }
    if (value == jcu::Script::CHAM) { return "CHAM"; }
    if (value == jcu::Script::KALI) { return "KALI"; }
    if (value == jcu::Script::LEPC) { return "LEPC"; }
    if (value == jcu::Script::LYCI) { return "LYCI"; }
    if (value == jcu::Script::LYDI) { return "LYDI"; }
    if (value == jcu::Script::OLCK) { return "OLCK"; }
    if (value == jcu::Script::RJNG) { return "RJNG"; }
    if (value == jcu::Script::SAUR) { return "SAUR"; }
    if (value == jcu::Script::SUND) { return "SUND"; }
    if (value == jcu::Script::VAII) { return "VAII"; }
    if (value == jcu::Script::ARMI) { return "ARMI"; }
    if (value == jcu::Script::AVST) { return "AVST"; }
    if (value == jcu::Script::BAMU) { return "BAMU"; }
    if (value == jcu::Script::EGYP) { return "EGYP"; }
    if (value == jcu::Script::JAVA) { return "JAVA"; }
    if (value == jcu::Script::KTHI) { return "KTHI"; }
    if (value == jcu::Script::LANA) { return "LANA"; }
    if (value == jcu::Script::LISU) { return "LISU"; }
    if (value == jcu::Script::MTEI) { return "MTEI"; }
    if (value == jcu::Script::ORKH) { return "ORKH"; }
    if (value == jcu::Script::PHLI) { return "PHLI"; }
    if (value == jcu::Script::PRTI) { return "PRTI"; }
    if (value == jcu::Script::SAMR) { return "SAMR"; }
    if (value == jcu::Script::SARB) { return "SARB"; }
    if (value == jcu::Script::TAVT) { return "TAVT"; }
    if (value == jcu::Script::BATK) { return "BATK"; }
    if (value == jcu::Script::BRAH) { return "BRAH"; }
    if (value == jcu::Script::MAND) { return "MAND"; }
    if (value == jcu::Script::CAKM) { return "CAKM"; }
    if (value == jcu::Script::MERC) { return "MERC"; }
    if (value == jcu::Script::MERO) { return "MERO"; }
    if (value == jcu::Script::PLRD) { return "PLRD"; }
    if (value == jcu::Script::SHRD) { return "SHRD"; }
    if (value == jcu::Script::SORA) { return "SORA"; }
    if (value == jcu::Script::TAKR) { return "TAKR"; }
    if (value == jcu::Script::AGHB) { return "AGHB"; }
    if (value == jcu::Script::BASS) { return "BASS"; }
    if (value == jcu::Script::DUPL) { return "DUPL"; }
    if (value == jcu::Script::ELBA) { return "ELBA"; }
    if (value == jcu::Script::GRAN) { return "GRAN"; }
    if (value == jcu::Script::HMNG) { return "HMNG"; }
    if (value == jcu::Script::KHOJ) { return "KHOJ"; }
    if (value == jcu::Script::LINA) { return "LINA"; }
    if (value == jcu::Script::MAHJ) { return "MAHJ"; }
    if (value == jcu::Script::MANI) { return "MANI"; }
    if (value == jcu::Script::MEND) { return "MEND"; }
    if (value == jcu::Script::MODI) { return "MODI"; }
    if (value == jcu::Script::MROO) { return "MROO"; }
    if (value == jcu::Script::NARB) { return "NARB"; }
    if (value == jcu::Script::NBAT) { return "NBAT"; }
    if (value == jcu::Script::PALM) { return "PALM"; }
    if (value == jcu::Script::PAUC) { return "PAUC"; }
    if (value == jcu::Script::PERM) { return "PERM"; }
    if (value == jcu::Script::PHLP) { return "PHLP"; }
    if (value == jcu::Script::SIDD) { return "SIDD"; }
    if (value == jcu::Script::SIND) { return "SIND"; }
    if (value == jcu::Script::TIRH) { return "TIRH"; }
    if (value == jcu::Script::WARA) { return "WARA"; }
    if (value == jcu::Script::AHOM) { return "AHOM"; }
    if (value == jcu::Script::HATR) { return "HATR"; }
    if (value == jcu::Script::HLUW) { return "HLUW"; }
    if (value == jcu::Script::HUNG) { return "HUNG"; }
    if (value == jcu::Script::MULT) { return "MULT"; }
    if (value == jcu::Script::SGNW) { return "SGNW"; }
    if (value == jcu::Script::ADLM) { return "ADLM"; }
    if (value == jcu::Script::BHKS) { return "BHKS"; }
    if (value == jcu::Script::MARC) { return "MARC"; }
    if (value == jcu::Script::NEWA) { return "NEWA"; }
    if (value == jcu::Script::OSGE) { return "OSGE"; }
    if (value == jcu::Script::TANG) { return "TANG"; }
    if (value == jcu::Script::GONM) { return "GONM"; }
    if (value == jcu::Script::NSHU) { return "NSHU"; }
    if (value == jcu::Script::SOYO) { return "SOYO"; }
    if (value == jcu::Script::ZANB) { return "ZANB"; }
    if (value == jcu::Script::DOGR) { return "DOGR"; }
    if (value == jcu::Script::GONG) { return "GONG"; }
    if (value == jcu::Script::MAKA) { return "MAKA"; }
    if (value == jcu::Script::MEDF) { return "MEDF"; }
    if (value == jcu::Script::ROHG) { return "ROHG"; }
    if (value == jcu::Script::SOGD) { return "SOGD"; }
    if (value == jcu::Script::SOGO) { return "SOGO"; }
    if (value == jcu::Script::ELYM) { return "ELYM"; }
    if (value == jcu::Script::HMNP) { return "HMNP"; }
    if (value == jcu::Script::NAND) { return "NAND"; }
    if (value == jcu::Script::WCHO) { return "WCHO"; }
    if (value == jcu::Script::CHRS) { return "CHRS"; }
    if (value == jcu::Script::DIAK) { return "DIAK"; }
    if (value == jcu::Script::KITS) { return "KITS"; }
    if (value == jcu::Script::YEZI) { return "YEZI"; }
    if (value == jcu::Script::CPMN) { return "CPMN"; }
    if (value == jcu::Script::OUGR) { return "OUGR"; }
    if (value == jcu::Script::TNSA) { return "TNSA"; }
    if (value == jcu::Script::TOTO) { return "TOTO"; }
    if (value == jcu::Script::VITH) { return "VITH"; }
    if (value == jcu::Script::KAWI) { return "KAWI"; }
    if (value == jcu::Script::NAGM) { return "NAGM"; }
    if (value == jcu::Script::GARA) { return "GARA"; }
    if (value == jcu::Script::GUKH) { return "GUKH"; }
    if (value == jcu::Script::KRAI) { return "KRAI"; }
    if (value == jcu::Script::ONAO) { return "ONAO"; }
    if (value == jcu::Script::SUNU) { return "SUNU"; }
    if (value == jcu::Script::TODR) { return "TODR"; }
    if (value == jcu::Script::TUTG) { return "TUTG"; }
    return "NIL";
}


constexpr std::string ToString(jcu::Script value) {
    if (value == jcu::Script::ZINH) { return "Inherited"; }
    if (value == jcu::Script::ZYYY) { return "Common"; }
    if (value == jcu::Script::ZZZZ) { return "Unknown"; }
    if (value == jcu::Script::ARAB) { return "Arabic"; }
    if (value == jcu::Script::ARMN) { return "Armenian"; }
    if (value == jcu::Script::BENG) { return "Bengali"; }
    if (value == jcu::Script::BOPO) { return "Bopomofo"; }
    if (value == jcu::Script::CYRL) { return "Cyrillic"; }
    if (value == jcu::Script::DEVA) { return "Devanagari"; }
    if (value == jcu::Script::GEOR) { return "Georgian"; }
    if (value == jcu::Script::GREK) { return "Greek"; }
    if (value == jcu::Script::GUJR) { return "Gujarati"; }
    if (value == jcu::Script::GURU) { return "Gurmukhi"; }
    if (value == jcu::Script::HANG) { return "Hangul"; }
    if (value == jcu::Script::HANI) { return "Han"; }
    if (value == jcu::Script::HEBR) { return "Hebrew"; }
    if (value == jcu::Script::HIRA) { return "Hiragana"; }
    if (value == jcu::Script::KANA) { return "Katakana"; }
    if (value == jcu::Script::KNDA) { return "Kannada"; }
    if (value == jcu::Script::LAOO) { return "Lao"; }
    if (value == jcu::Script::LATN) { return "Latin"; }
    if (value == jcu::Script::MLYM) { return "Malayalam"; }
    if (value == jcu::Script::ORYA) { return "Oriya"; }
    if (value == jcu::Script::TAML) { return "Tamil"; }
    if (value == jcu::Script::TELU) { return "Telugu"; }
    if (value == jcu::Script::THAI) { return "Thai"; }
    if (value == jcu::Script::TIBT) { return "Tibetan"; }
    if (value == jcu::Script::BRAI) { return "Braille"; }
    if (value == jcu::Script::CANS) { return "Canadian_Aboriginal"; }
    if (value == jcu::Script::CHER) { return "Cherokee"; }
    if (value == jcu::Script::ETHI) { return "Ethiopic"; }
    if (value == jcu::Script::KHMR) { return "Khmer"; }
    if (value == jcu::Script::MONG) { return "Mongolian"; }
    if (value == jcu::Script::MYMR) { return "Myanmar"; }
    if (value == jcu::Script::OGAM) { return "Ogham"; }
    if (value == jcu::Script::RUNR) { return "Runic"; }
    if (value == jcu::Script::SINH) { return "Sinhala"; }
    if (value == jcu::Script::SYRC) { return "Syriac"; }
    if (value == jcu::Script::THAA) { return "Thaana"; }
    if (value == jcu::Script::YIII) { return "Yi"; }
    if (value == jcu::Script::DSRT) { return "Deseret"; }
    if (value == jcu::Script::GOTH) { return "Gothic"; }
    if (value == jcu::Script::ITAL) { return "Old_Italic"; }
    if (value == jcu::Script::BUHD) { return "Buhid"; }
    if (value == jcu::Script::HANO) { return "Hanunoo"; }
    if (value == jcu::Script::TAGB) { return "Tagbanwa"; }
    if (value == jcu::Script::TGLG) { return "Tagalog"; }
    if (value == jcu::Script::CPRT) { return "Cypriot"; }
    if (value == jcu::Script::LIMB) { return "Limbu"; }
    if (value == jcu::Script::LINB) { return "Linear_B"; }
    if (value == jcu::Script::OSMA) { return "Osmanya"; }
    if (value == jcu::Script::SHAW) { return "Shavian"; }
    if (value == jcu::Script::TALE) { return "Tai_Le"; }
    if (value == jcu::Script::UGAR) { return "Ugaritic"; }
    if (value == jcu::Script::BUGI) { return "Buginese"; }
    if (value == jcu::Script::COPT) { return "Coptic"; }
    if (value == jcu::Script::GLAG) { return "Glagolitic"; }
    if (value == jcu::Script::KHAR) { return "Kharoshthi"; }
    if (value == jcu::Script::SYLO) { return "Syloti_Nagri"; }
    if (value == jcu::Script::TALU) { return "New_Tai_Lue"; }
    if (value == jcu::Script::TFNG) { return "Tifinagh"; }
    if (value == jcu::Script::XPEO) { return "Old_Persian"; }
    if (value == jcu::Script::BALI) { return "Balinese"; }
    if (value == jcu::Script::NKOO) { return "Nko"; }
    if (value == jcu::Script::PHAG) { return "Phags_Pa"; }
    if (value == jcu::Script::PHNX) { return "Phoenician"; }
    if (value == jcu::Script::XSUX) { return "Cuneiform"; }
    if (value == jcu::Script::CARI) { return "Carian"; }
    if (value == jcu::Script::CHAM) { return "Cham"; }
    if (value == jcu::Script::KALI) { return "Kayah_Li"; }
    if (value == jcu::Script::LEPC) { return "Lepcha"; }
    if (value == jcu::Script::LYCI) { return "Lycian"; }
    if (value == jcu::Script::LYDI) { return "Lydian"; }
    if (value == jcu::Script::OLCK) { return "Ol_Chiki"; }
    if (value == jcu::Script::RJNG) { return "Rejang"; }
    if (value == jcu::Script::SAUR) { return "Saurashtra"; }
    if (value == jcu::Script::SUND) { return "Sundanese"; }
    if (value == jcu::Script::VAII) { return "Vai"; }
    if (value == jcu::Script::ARMI) { return "Imperial_Aramaic"; }
    if (value == jcu::Script::AVST) { return "Avestan"; }
    if (value == jcu::Script::BAMU) { return "Bamum"; }
    if (value == jcu::Script::EGYP) { return "Egyptian_Hieroglyphs"; }
    if (value == jcu::Script::JAVA) { return "Javanese"; }
    if (value == jcu::Script::KTHI) { return "Kaithi"; }
    if (value == jcu::Script::LANA) { return "Tai_Tham"; }
    if (value == jcu::Script::LISU) { return "Lisu"; }
    if (value == jcu::Script::MTEI) { return "Meetei_Mayek"; }
    if (value == jcu::Script::ORKH) { return "Old_Turkic"; }
    if (value == jcu::Script::PHLI) { return "Inscriptional_Pahlavi"; }
    if (value == jcu::Script::PRTI) { return "Inscriptional_Parthian"; }
    if (value == jcu::Script::SAMR) { return "Samaritan"; }
    if (value == jcu::Script::SARB) { return "Old_South_Arabian"; }
    if (value == jcu::Script::TAVT) { return "Tai_Viet"; }
    if (value == jcu::Script::BATK) { return "Batak"; }
    if (value == jcu::Script::BRAH) { return "Brahmi"; }
    if (value == jcu::Script::MAND) { return "Mandaic"; }
    if (value == jcu::Script::CAKM) { return "Chakma"; }
    if (value == jcu::Script::MERC) { return "Meroitic_Cursive"; }
    if (value == jcu::Script::MERO) { return "Meroitic_Hieroglyphs"; }
    if (value == jcu::Script::PLRD) { return "Miao"; }
    if (value == jcu::Script::SHRD) { return "Sharada"; }
    if (value == jcu::Script::SORA) { return "Sora_Sompeng"; }
    if (value == jcu::Script::TAKR) { return "Takri"; }
    if (value == jcu::Script::AGHB) { return "Caucasian_Albanian"; }
    if (value == jcu::Script::BASS) { return "Bassa_Vah"; }
    if (value == jcu::Script::DUPL) { return "Duployan"; }
    if (value == jcu::Script::ELBA) { return "Elbasan"; }
    if (value == jcu::Script::GRAN) { return "Grantha"; }
    if (value == jcu::Script::HMNG) { return "Pahawh_Hmong"; }
    if (value == jcu::Script::KHOJ) { return "Khojki"; }
    if (value == jcu::Script::LINA) { return "Linear_A"; }
    if (value == jcu::Script::MAHJ) { return "Mahajani"; }
    if (value == jcu::Script::MANI) { return "Manichaean"; }
    if (value == jcu::Script::MEND) { return "Mende_Kikakui"; }
    if (value == jcu::Script::MODI) { return "Modi"; }
    if (value == jcu::Script::MROO) { return "Mro"; }
    if (value == jcu::Script::NARB) { return "Old_North_Arabian"; }
    if (value == jcu::Script::NBAT) { return "Nabataean"; }
    if (value == jcu::Script::PALM) { return "Palmyrene"; }
    if (value == jcu::Script::PAUC) { return "Pau_Cin_Hau"; }
    if (value == jcu::Script::PERM) { return "Old_Permic"; }
    if (value == jcu::Script::PHLP) { return "Psalter_Pahlavi"; }
    if (value == jcu::Script::SIDD) { return "Siddham"; }
    if (value == jcu::Script::SIND) { return "Khudawadi"; }
    if (value == jcu::Script::TIRH) { return "Tirhuta"; }
    if (value == jcu::Script::WARA) { return "Warang_Citi"; }
    if (value == jcu::Script::AHOM) { return "Ahom"; }
    if (value == jcu::Script::HATR) { return "Hatran"; }
    if (value == jcu::Script::HLUW) { return "Anatolian_Hieroglyphs"; }
    if (value == jcu::Script::HUNG) { return "Old_Hungarian"; }
    if (value == jcu::Script::MULT) { return "Multani"; }
    if (value == jcu::Script::SGNW) { return "SignWriting"; }
    if (value == jcu::Script::ADLM) { return "Adlam"; }
    if (value == jcu::Script::BHKS) { return "Bhaiksuki"; }
    if (value == jcu::Script::MARC) { return "Marchen"; }
    if (value == jcu::Script::NEWA) { return "Newa"; }
    if (value == jcu::Script::OSGE) { return "Osage"; }
    if (value == jcu::Script::TANG) { return "Tangut"; }
    if (value == jcu::Script::GONM) { return "Masaram_Gondi"; }
    if (value == jcu::Script::NSHU) { return "Nushu"; }
    if (value == jcu::Script::SOYO) { return "Soyombo"; }
    if (value == jcu::Script::ZANB) { return "Zanabazar_Square"; }
    if (value == jcu::Script::DOGR) { return "Dogra"; }
    if (value == jcu::Script::GONG) { return "Gunjala_Gondi"; }
    if (value == jcu::Script::MAKA) { return "Makasar"; }
    if (value == jcu::Script::MEDF) { return "Medefaidrin"; }
    if (value == jcu::Script::ROHG) { return "Hanifi_Rohingya"; }
    if (value == jcu::Script::SOGD) { return "Sogdian"; }
    if (value == jcu::Script::SOGO) { return "Old_Sogdian"; }
    if (value == jcu::Script::ELYM) { return "Elymaic"; }
    if (value == jcu::Script::HMNP) { return "Nyiakeng_Puachue_Hmong"; }
    if (value == jcu::Script::NAND) { return "Nandinagari"; }
    if (value == jcu::Script::WCHO) { return "Wancho"; }
    if (value == jcu::Script::CHRS) { return "Chorasmian"; }
    if (value == jcu::Script::DIAK) { return "Dives_Akuru"; }
    if (value == jcu::Script::KITS) { return "Khitan_Small_jcu::Script"; }
    if (value == jcu::Script::YEZI) { return "Yezidi"; }
    if (value == jcu::Script::CPMN) { return "Cypro_Minoan"; }
    if (value == jcu::Script::OUGR) { return "Old_Uyghur"; }
    if (value == jcu::Script::TNSA) { return "Tangsa"; }
    if (value == jcu::Script::TOTO) { return "Toto"; }
    if (value == jcu::Script::VITH) { return "Vithkuqi"; }
    if (value == jcu::Script::KAWI) { return "Kawi"; }
    if (value == jcu::Script::NAGM) { return "Nag_Mundari"; }
    if (value == jcu::Script::GARA) { return "Garay"; }
    if (value == jcu::Script::GUKH) { return "Gurung_Khema"; }
    if (value == jcu::Script::KRAI) { return "Kirat_Rai"; }
    if (value == jcu::Script::ONAO) { return "Ol_Onal"; }
    if (value == jcu::Script::SUNU) { return "Sunuwar"; }
    if (value == jcu::Script::TODR) { return "Todhri"; }
    if (value == jcu::Script::TUTG) { return "Tulu_Tigalari"; }
    return "NIL";
}


}
